### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by IARI** [ultimate-pa/ultimate#1]
I'm on Ubuntu 14.04 (Gnome Shel 3.10.4)
I installed Eclipse CDT (Mars)
I installed ultimate according to the [instructions](https://github.com/ultimate-pa/ultimate/wiki/Installation)

After importing the Projects, there are 57 errors in the Projects *SpaceExParser, Website, WebstieEclipseBridge* - see screenshot.

Assuming this is normal and not critical:
 * This might confuse people (as it does me) when there are other problems with the installation process - I would strongly recommend adding that as a side note to the installation instruction page.

otherwise
 * What is possibly missing/wrong with my installation?

Secondly the **Create Run Configuration** part failed.
After clicking "Launch an Eclipse application", the launch process fails.
[error log on pastebin](http://pastebin.com/vSpgZrRj) (Sadly github fails to accept the log file.)

![screenshot from 2015-09-25 22 33 57](https://cloud.githubusercontent.com/assets/1053417/10111628/a3b5b58a-63d5-11e5-96c7-d579b396fa36.png)

![eclipseinstall](https://cloud.githubusercontent.com/assets/1053417/10119126/8b4a52d6-648d-11e5-93af-57b7cda28e1e.png)

**Comment by Heizmann** [comment]
Thanks for reporting this. It is not normal. However, yet I do not have an idea.

**Comment by danieldietsch** [comment]
Can you post the details for your Eclipse installation, i.e., Help -> Eclipse -> Installation Details -> Installed Software?

**Comment by IARI** [comment]
I added a Screenshot @danieldietsch

**Comment by IARI** [comment]
I checked the [Troubleshooting](https://github.com/ultimate-pa/ultimate/wiki/Troubleshooting) guide.
There were two plugin problems, see screenshot.
However, checking the corresponding packages and unchecking optional dependencies didn't fix the problem.

![plugins](https://cloud.githubusercontent.com/assets/1053417/10122377/a71fcad8-6517-11e5-83c1-cafb99fb61db.png)

**Comment by danieldietsch** [comment]
Ok, I looked at the errors and the problem(s). Unfortunately, this (being a working Launch Configuration / Product file) will take longer to fix. We have to migrate (properly) to Eclipse4. 

I will leave this open to remind me about it, but expect it to be fixed more later than sooner. Nevertheless you can use Ultimate in Eclipse4 and you already took the right steps. I suspect after your changes to the plugin configuration, your error log has slightly changed. Can you post the new log on pastebin? 

I suspect that you have to add the platform SWT bindings...

**Comment by IARI** [comment]
sure - here you go.
http://pastebin.com/fRAzen6Y

Now how do I do that (add platform SWT bindings)?

**Comment by danieldietsch** [comment]
But you added org.eclipse.e4.core.di.annotations to the Launch configuration you are using?

**Comment by IARI** [comment]
Yes I did. Meanwhile I did a git update, deleted my run config and repeated the process from there. And there is a new Problem:
The plugin dependency org.eclipse.equinox.p2 cannot be satisfied.

(will add screenshots later)

**Comment by danieldietsch** [comment]
We could also try and use Teamviewer or something s.t. I can have a look and fix the problem right away.

**Comment by IARI** [comment]
absolutely. i have it installed and running, but I'm accessing it myself from my laptop because I'm in Matthias office right now. would you have time in about an hour?

**Comment by danieldietsch** [comment]
@IARI is fixed for now, but the real bug is still present

**Comment by greitsch** [comment]
I was having the same problem on two separate machines just a few days ago.

Validating the plug-ins and instructing Eclipse to import all needed plug-ins in the run configuration solved it for me (see Screenshot).

**Comment by danieldietsch** [comment]
This issue does no longer persist.
