### ISSUE TITLE
Support "new" SVCOMP file keywords in SafetyTestResultDecider

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#101]
E.g. Inconsistent keywords
		Input:svcomp/forester-heap/dll-rb-cnstr_1_false-unreach-call_true-valid-memsafety.i Settings:settings/ai/svcomp-Reach-32bit-Automizer_Default+AIv2_COMP_Simple.epf Toolchain:toolchains/AutomizerC.xml
			Error: annotation given by keywords is inconsitent

**Comment by Heizmann** [comment]
Use either SvcompMemsafetyTestResultDecider, SvcompOverflowTestResultDecider, or SvcompReachTestResultDecider instead of SafetyCheckTestResultDecider.
