### ISSUE TITLE
Support line directives in counterexamples

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#111]
C contains line directives: <code>#line</code>:
To relate cilled file with the original sources we want to print line numbers according to line directives. 
This may be a bit tricky, because CDT does not support this out of the box.

**Comment by danieldietsch** [comment]
CPAchecker interprets #line directives with "parser.readLineDirectives=true" or if CPAChecker calls the preprocessor, "parser.usePreprocessor=true"

Internally, one can view their implementation around https://github.com/sosy-lab/cpachecker/blob/trunk/src/org/sosy_lab/cpachecker/cfa/CParserWithLocationMapper.java

**Comment by danieldietsch** [comment]
@Heizmann I think you fixed this, right?

**Comment by Heizmann** [comment]
Yes
