### ISSUE TITLE
BoogiePreprocessor backtranslation faulty

### ISSUE THREAD

**Issue by Langenfeld** [ultimate-pa/ultimate#12]
The backtranslation uses wrong variable names in the FailurePath's states.

For example [boogiePrinter.zip](https://github.com/ultimate-pa/ultimate/files/118936/boogiePrinter.zip)(analyzed with AutomizerBPL toolchain):
[...,c=1, c=1, ...
should be something like
[..., pc0 = 1, pc1 = 1, ... .

**Comment by danieldietsch** [comment]
Cannot reproduce / already fixed
