### ISSUE TITLE
Next-step at End of program

### ISSUE THREAD

**Issue by Langenfeld** [ultimate-pa/ultimate#129]
Pending next state opreator at end of a program does not work properly. 
e.g.  a -> Xb 
always has a counterexample when a is set at end of program.

**Comment by danieldietsch** [comment]
@Langenfeld Is this not the intended behaviour? In our paper, we only consider infinite traces and model termination as staying forever in the last program state.

**Comment by Langenfeld** [comment]
@danieldietsch yes, we only consider infinite traces, extending finite tracs by a repetition of their last step. 
The question is following program safe?
```
//@ ltl invariant positive: [](AP(y == 1) ==> X(AP(x == 2) ));
int main()
{
	y = 1;
	__VERIFIER_ltl_step();
	x = 2;
	__VERIFIER_ltl_step();
}
```
When extending every finite trace to infinite this is safe ({y=1, x=*}. {y=1, x=2}^\omega). In step semantics this should be safe, too as the only counter example in this program may be  {y=1, x=*}. {y=1, x=/=2} (^\omega).

**Comment by danieldietsch** [comment]
I take it this program is not safe? If you add an example to the repo, I take a look.

**Comment by Langenfeld** [comment]
Already uploaded in LTL/regressions (https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/LTL/regression/stepwise/X_smaller_safe.c)

In the current version it is returning unsafe, in my opinion this should be safe.
