### ISSUE TITLE
SMT Sorts in Ultimate

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#152]
We have a new class for the handling of SMT sorts in Ultimate.
https://github.com/ultimate-pa/ultimate/commit/f57571a6b934c05a8c23e60694366e1bd6cfd5dc
TODO: Replace all occurrences in Ultimate where sorts are constructed or checked by the static strings and methods of this class

**Comment by danieldietsch** [comment]
@greitsch: this may potentially resolve #136; if you agree, please close #136.

**Comment by greitsch** [comment]
@danieldietsch It only resolves #136 if all references to strings are replaced with the references defined by f57571a.

**Comment by danieldietsch** [comment]
So you agree that if #152 is resolved, #136 is resolved?

**Comment by greitsch** [comment]
Yes. That's correct.
