### ISSUE TITLE
Overapproximation of bitwise operations

### ISSUE THREAD

**Issue by sergioafeo** [ultimate-pa/ultimate#154]
Currently, the translation of bitwise operations produces function stubs. E.g.,

    unsigned int something;
    something &= 0x7fffffff;

is translated to

    var ~something : int;
    ~something := ~bitwiseAnd(~something, 2147483647);
    function { :overapproximation "bitwiseAnd" } ~bitwiseAnd(in0 : int, in1 : int) returns (out : int);

Which is not very useful for verification.

At least for unsigned types, it would be good to have the option of using bitvector operations. Something along the lines of:

    var ~something : bv32;
    ~something := ~bitwiseAnd(~something, 2147483647bv32);
    function {:bvbuiltin "bvand"} ~bitwiseAnd(bv32,bv32) returns(bv32);

Similarly for other operations (add, sub, div, or, xor), which would map to the builtin functions of the [SMT-LIB v2 QF_BV Theory](http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_BV) . [[Source]](http://boogie-docs.readthedocs.io/en/latest/LangRef.html)

**Comment by danieldietsch** [comment]
Which settings do you use and how do you call Ultimate? 
If you use the GUI, try using settings from [examples/settings/default/automizer](https://github.com/ultimate-pa/ultimate/tree/dev/trunk/examples/settings/default/automizer) that match you architecture, property and precision (in this case, Bitvector).
We already map most bv functions to the appropriate bv theory symbols.

**Comment by sergioafeo** [comment]
Hier is an example program:
```C
int isTopBit(unsigned something)
{
	something &= 0x7fffffff;
    if (something & 0x80000000) {
		//@ assert (0);
		return 0;
	} else {
		return 1;
	}
}
```

Indeed, I had not discovered the option "use bitvectors instead of ints". When enabling that option (see attached options file) an exception is thrown:

```
[2017-04-07 14:21:45,565 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.rcfgbuilder has thrown an exception:
java.lang.AssertionError: de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: Sort BitVec not declared
```
[topbit.epf.txt](https://github.com/ultimate-pa/ultimate/files/905534/topbit.epf.txt)

**Comment by danieldietsch** [comment]
Ah, your setting is not enough. Are you on Linux? If so, reset your settings and load the settings file [trunk/examples/settings/default/automizer/svcomp-Reach-64bit-Automizer_Bitvector.epf](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/settings/default/automizer/svcomp-Reach-64bit-Automizer_Bitvector.epf).
If you are on Windows, you should try the attached settings (rename fileending from ``.epf.txt`` to ``.epf``). They are -- sadly -- not as effective, because there is currently no CVC4 version for Windows that is compatible with Ultimate. 
[svcomp-Reach-64bit-Automizer_Bitvector_Windows.epf.txt](https://github.com/ultimate-pa/ultimate/files/906049/svcomp-Reach-64bit-Automizer_Bitvector_Windows.epf.txt)

**Comment by sergioafeo** [comment]
Reset settings, loaded the epf provided, more exceptions (see log and bpl attached). 

[topbit_log.txt](https://github.com/ultimate-pa/ultimate/files/909357/topbit_log.txt)
[boogiePrinter.bpl.txt](https://github.com/ultimate-pa/ultimate/files/909359/boogiePrinter.bpl.txt)

**Comment by danieldietsch** [comment]
It seems you use an outdated version of z3. Did you compile the latest version from their repository?

**Comment by sergioafeo** [comment]
Linux with latest z3 works!
Windows with z3 4.50 works!

Thanks :)

PS: Is it recommended to assume that a `java.lang.UnsupportedOperationException` boils down to an issue with the SMT solver?

**Comment by greitsch** [comment]
> PS: Is it recommended to assume that a java.lang.UnsupportedOperationException boils down to an issue with the SMT solver?

No. We use UnsupportedOperationExceptions widely for UnsupportedOperations or for the lack of a better exception. ;-) Maybe, the Exceptions raised from SMT solver usages should be named differently, though.

**Comment by danieldietsch** [comment]
Yes, @greitsch is right. But you can assume that if you get an UnsupportedOperationException from ``de.uni_freiburg.informatik.ultimate.smtsolver.external.Parser`` it is SMT-related. The auto-generated code there throws this exception if an external solver reports an unsupported option (and older z3s do not support the ``ALL`` logic).
