### ISSUE TITLE
Testsuites Headless

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#164]
If I start a new Testsuite it is not in the Headless Mode

**Comment by danieldietsch** [comment]
I can check this evening. But what do you mean? Does the GUI open once for each test, or just once, or is it something entirely different?

Am 5. Mai 2017 23:17:13 MESZ schrieb Matthias Heizmann <notifications@github.com>:

**Comment by Heizmann** [comment]
Eclipse GUI opens once for each testsuite.
Can be avoided if you change for each testsuite in the runconfiguration
Main > Program to Run > Run a product
to
Main > Program to Run > Run an application > "[ No Application] - Headless Mode"
