### ISSUE TITLE
VPDomain: sound support for non-atomic, non-array accessing (e.g arithmetic) subterms

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#177]
Currently we have no way of finding a contradiction for example in the equality (x = x + 1).

**Comment by Heizmann** [comment]
If `(x = x + 1)` is given as Term, the CommuhashNormalForm will transform it to `false`

**Comment by alexandernutz** [comment]
(also the ticket is probably not really about soundness but rather about completeness, to be precise..)

**Comment by alexandernutz** [comment]
closing this as I am currently ok with our solution

current solution:
 - array select terms become functions in the congruence closure
 - constants and variables are "normal" nodes
 - boolean atoms with intern predicate symbols (like "<") are abstracted to "true"
 - other boolean atoms b are converted to "b = true"
 - complex terms that occur in an equation, besides select terms, are "boxed" into a "EqNonAtomicNode"
 - non atomic nodes are removed/projected from an abstract state if one of their components (eg. a variable) is removed
 - before the boxing we apply a series of normalizations, currently we first attempt to convert to an AffineTerm, and if that fails we apply CommuHashNormalForm
