### ISSUE TITLE
SmtLib-HORN to Horn Clause Graph plugin

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#18]
Write a fresh Ultimate plugin which takes a smtlib-file which uses "set-logic HORN" and builds the Horn Clause graph from it.
See also
https://github.com/ultimate-pa/ultimate/wiki/Tree-Automizer

Subtasks
- Integrate smtlib-parser into Ultimate
- implement conversion to a hyper graph
  - edges are labelled with a variant of TransitionFormula
  - nodes correspond to uninterpreted predicate symbols
    (..)

1 week
create a plugin "HornClauseGraphBuilder"
  procedure right now:
   copy an existing one, that is similar (RCFGBuilder), delete all code, except base classes (.. Activator, ~Observer, ~.java) rename in every place, also in plugin.xml
use smtlib2 parser from smtInterpol
  alex: find out how to get the parser into ultimate
build the graph
  alex: organize the graph base classes

**Comment by mostafa-mahmoud** [comment]
The commit e6424b9d969cd9119d2d9688698b14631e9af6e9 now works successfully in parsing the simple file that we had earlier, and converting it to HornClauses. There is a strong assumption on the format of the implications, so I think that you should send me more files, to handle more general forms if needed.

**Comment by mostafa-mahmoud** [comment]
The Graphbuilder throws an exception though, but I didn't start working on it yet.

**Comment by alexandernutz** [comment]
I added an example that  we cannot parse yet in commit ultimate-pa/ultimate@90cdbec9bdac0e00053f702868983c21572d6eb3
