### ISSUE TITLE
Add support for error automata in Automizer

### ISSUE THREAD

**Issue by schillic** [ultimate-pa/ultimate#182]
An error automaton generalizes an error, just as an interpolant automaton generalizes a reason for infeasibility.
By taking the difference of the abstraction and an error automaton we can continue with the analysis "up to this error".

There have already been three commits related to this issue: [1](https://github.com/ultimate-pa/ultimate/commit/57f4b0d3f2226523bfc85ef2daf106f67596bc3d), [2](https://github.com/ultimate-pa/ultimate/commit/5e949f8e5092b77b1fecfebf26d3f848fa97bd50), [3](https://github.com/ultimate-pa/ultimate/commit/da9248a4c22965f53c2797bd207ae278e088bd41)

**Comment by schillic** [comment]
@Heizmann: Can we close this?

**Comment by Heizmann** [comment]
I don't know.

**Comment by schillic** [comment]
Then we can :)
