### ISSUE TITLE
Repository for automata benchmarks

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#183]
We need a repository for automata benchmarks.
I already created one. https://github.com/ultimate-pa/automata-benchmarks
Please let me know if you don't like it.

What license should we use for the automata benchmarks?
I have the impression that the typical licenses for source code are not appropriate/applicable and it would be better to pick a creative commons license.
I would prefer that we try to minimize the number of licenses in this benchmark repository. My plan is to pick [Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/) for benchmarks that I create. Any objections?

**Comment by greitsch** [comment]
Why not use https://github.com/ultimate-pa/ultimate-benchmarks and do a sparse checkout like is the case with the SVCOMP-Repository?

But I haven't any strong opinion about this, besides that having multiple benchmark repositories decreases overview.

**Comment by Heizmann** [comment]
Sparse checkouts are more complicated. I would like to have separate repositories for different user groups.
(Why did we introduce ultimate-benchmarks at all? We could put everything into one repository and do sparse checkouts.)

**Comment by danieldietsch** [comment]
I agree with both proposals: Attribution-ShareAlike license and separate repository.

**Comment by danieldietsch** [comment]
@Heizmann : is this ticket finished?

**Comment by Heizmann** [comment]
If no one has further opinions on the license that I should use, we can close it.
