### ISSUE TITLE
Conceptual Problem in CACSL2BoogieBacktranslator

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#187]
@danieldietsch  You cannot use the BoogieToC backtranslation of identifiers and construct an IdentifierExpression with the resulting string as you do in [line 1277 of CACSL2BoogieBacktranslator](https://github.com/ultimate-pa/ultimate/blob/76e893181b51bd82c95b710ab243d6ca168645d5/trunk/source/CACSL2BoogieTranslator/src/de/uni_freiburg/informatik/ultimate/plugins/generator/cacsl2boogietranslator/CACSL2BoogieBacktranslator.java#L1277).

The BoogieToC backtranslation of identifiers constructs e.g., expressions like \old() which are not valid Boogie identifiers.
This problem lets several regressions tests fail. E.g., examples/programs/regression/c/interprocedural/Jungfrau-Safe.c Reproducible with AutomizerC.xml toolchain and default settings.

**Comment by danieldietsch** [comment]
You are right. This was a dirty hack at some point.

**Comment by danieldietsch** [comment]
Default settings do not reproduce; you have to enable the Hoare annotation production.
