### ISSUE TITLE
Unhelpful error when analyzing a C file with a Boogie toolchain

### ISSUE THREAD

**Issue by schillic** [ultimate-pa/ultimate#193]
When analyzing a Boogie file with a C toolchain there is an UnsupportedOperationException saying "Your input file is a Boogie program. This plugin takes as input a C program."
Great!

When analyzing a C file with a Boogie toolchain there is an UnsupportedOperationException without any comment:
de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:90)
Not helpful!

It would be more consistent and user-friendly if the latter also exited with a nice message; at least the tool should say that the file is not a Boogie program, then in 99% the user should be able to see the mistake.

**Comment by Heizmann** [comment]
I agree. There should be a better error message.
