### ISSUE TITLE
Commit local .gitignore files?

### ISSUE THREAD

**Issue by sergioafeo** [ultimate-pa/ultimate#2]
Eclipse 4 creates by default .gitignore in most directories to avoid tracking the /bin subdirectories. Shouldn't those be commited to the repository anyway? How do you handle them otherwise?

**Comment by danieldietsch** [comment]
No. 
For me, Eclipse does not do that. 
We handle the ignoring with a .gitignore at the root.

**Comment by greitsch** [comment]
@sergioafeo Maybe the solution is to disable the checkbox "Automatically ignore derived resources by adding them to .gitignore" (see Screenshot). Can you verify?

![gitignores](https://cloud.githubusercontent.com/assets/10132448/10546303/884dc3ce-742d-11e5-9a14-505bc5d0393a.png)

**Comment by danieldietsch** [comment]
Do you use the eclipse plugin for the various git operations or your command line?

**Comment by greitsch** [comment]
I use the git command line almost exclusively. But even if I use the Eclipse plug-in, the .gitignores are shown.

Unfortunately, I didn't have the time yet to look into this issue further, yet.

**Comment by danieldietsch** [comment]
For me, .gitignore files are created when I switch a branch from the commandline and there are different project sets. When I switch branches with the Eclipse plugin, the files are not created. 

Again, I see this as an non-issue.

**Comment by greitsch** [comment]
It is an issue in the sense that it might happen that people commit those .gitignores which might interfere with the global .gitignore in the root directory. I'm trying to avoid this by finding a configuration combination that prevents those internal .gitignores from being created.

**Comment by greitsch** [comment]
According to @schillic the issue is solved by disabling the third option as seen in the screenshot of my earlier post (https://github.com/ultimate-pa/ultimate/issues/2#issuecomment-148750867).

We should add this to the documentation s.t. everyone installing Ultimate will have the correct settings for git.

**Comment by sergioafeo** [comment]
I can confirm disabling that setting works. Even after switching branches, the local .gitignore files are not recreated. This should definitely go into the install doc. Or is there a way to ship eclipse settings with the code?

**Comment by greitsch** [comment]
I created a sub section in the installation instructions which addresses this issue. Therefore, we're closed.
