### ISSUE TITLE
Wiki page on adding new developers is outdated

### ISSUE THREAD

**Issue by greitsch** [ultimate-pa/ultimate#20]
Currently, the Ultimate-Wiki page https://github.com/ultimate-pa/ultimate/wiki/AddDeveloper is outdated. This page needs to be revised and altered to reflect the current state Ultimate's repositories.

**Comment by Heizmann** [comment]
I think I fixed it.
https://github.com/ultimate-pa/ultimate/wiki/CodingConvention
