### ISSUE TITLE
HeapSeparator: scoping of Abstract Interpretation prohibits inference of relations between many pointer variables

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#211]
Say we have two procedures foo, bar.
foo mallocs a pointer p
bar mallocs a pointer q
at some locations we dereference p and q
Can we use a different memory-array for p and q?

answer:
We could, but in order for the HeapSeparator to  separate mem into two, we need to know that p!=q at each access of mem at either p or q. 

Problem:
our analysis never derives a relation between local variables from different scopes

**Comment by danieldietsch** [comment]
We could add some mechanism that ignores scoping and just adds all variables of the program to every abstract state, but this seems rather expensive. 
And is this what you are proposing? 

I mean, I would expect that you track all the indices for the global heap array in some way, and that each malloc gives you a "fresh" index. 
You then track which actual program variables point to this index. The indices themselves are global, and so you can have relations with all the locals (and transitively, with different scopes).
Is this not enough?

**Comment by alexandernutz** [comment]
On paragraph 1: I agree, it seems unnecessarily expensive to do that, but viable in principle.

On paragraph 2: I'm not totally sure I understand what you are saying, but "the indices themselves are global" does not seem true, right now. 
the array test file in SHA fceab837623a979d5a277bc3e78aac6d9ba50499 is not separated currently, for example

current plan: Add the "StoreIndexExposer", an icfgTransformer which introduces extra global variables into which each store index is nondeterministically copied. That seems relatively easy to do and would be close to your proposal/description, I guess.

**Comment by danieldietsch** [comment]
Wouldnt it be more useful to add these global indices directly in the abstraction instead as a preprocessing step?

**Comment by alexandernutz** [comment]
What would be the difference in usefulness? I don't see it right now.
It just seemed the simplest solution to implement, but maybe I should look into the domain solution closer..
It should still be possible to return the program without the extra variables from the HeapSeparator, so I would say it's the first, but perhaps not last, solution to our problem. (if it turns out to be a solution)

**Comment by danieldietsch** [comment]
It might be more flexible if used in the abstraction -- we could run multiple domains in parallel without having to worry about the additional variables. But if you already know how to implement it with this ``StoreIndexExposer``, then go ahead.

**Comment by danieldietsch** [comment]
@alexandernutz ois this ticket still open?

**Comment by alexandernutz** [comment]
Well.. I would say "yes".
We still do not know exactly why the HeapSeparator does not separate well and this might be one of the reasons.

**Comment by danieldietsch** [comment]
But istn the whole point of your equality domain that you are able to overcome this issue?

**Comment by alexandernutz** [comment]
yeah.. maybe..
I'm just saying: I don't yet understand fully what is going on during heapseparation, and this issue may or may not be related to that..

**Comment by alexandernutz** [comment]
Should be dealt with by either of the preprocessings (and adapted heap separations) from #295 (freeze var style or memloc array style).
