### ISSUE TITLE
Update wiki to newest Eclipse version (Oxygen)

### ISSUE THREAD

**Issue by schillic** [ultimate-pa/ultimate#212]
The wiki pages for [installation](https://github.com/ultimate-pa/ultimate/wiki/Installation) and [SonarLint configuration](https://github.com/ultimate-pa/ultimate/wiki/CodingConvention) should be updated to the most recent Eclipse version "Oxygen". I have just installed and tested it and stumbled upon the following problem.
* The current version of SonarLint (1.15.0.v20170411) requires a password.
Can we set a dummy password?

**Comment by danieldietsch** [comment]
I think we can setup a dummy user. But I noticed more problems: The received issues do not match the issues from the webinterface. 

Perhaps a Sonar update is necessary. @greitsch  did this for sopra recently. I am unsure if he already did it for Ultimate.

**Comment by schillic** [comment]
@danieldietsch: I think we left this one open for a reason, but I cannot remember.
Can we close?

**Comment by danieldietsch** [comment]
I think so
