### ISSUE TITLE
Update Sonar to latest version and add shared user

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#214]
see also #212

**Comment by danieldietsch** [comment]
Probably also a good idea: Update Jenkins.

**Comment by greitsch** [comment]
> Probably also a good idea: Update Jenkins.

This always comes in tandem ;-)

**Comment by greitsch** [comment]
All done and Wiki [updated](https://github.com/ultimate-pa/ultimate/wiki/Eclipse-Tweaks-&-Utilities#server-configuration).
