### ISSUE TITLE
Cannot execute Ultimate that was built with maven

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#22]
see [logfile](https://github.com/ultimate-pa/ultimate/files/312787/1465854857938.log.txt)

**Comment by Heizmann** [comment]
On my desktop computer at home I cannot reproduce the problem either.

The ultimate.ini that I am using on my laptop (where I have this problem) is the same as on my desktop computer and contains the following.
```
--launcher.suppressErrors
-nosplash
-consoleLog
--console
-data
@user.home/.ultimate
-vmargs
-Xmx12G
-Xms512M
```
I already removed the ~/.ultimate folder. I started Ultimate directly.

**Comment by danieldietsch** [comment]
So far, the problem did not occur anywhere else. I suppose it was some kind of cache corruption.
