### ISSUE TITLE
Get Rid of IBoogieVar in AbstractInterpretation

### ISSUE THREAD

**Issue by greitsch** [ultimate-pa/ultimate#222]
Currently, abstract interpretation uses the IBoogieVar interface to identify variables if analyzing ICFGs that stem from Boogie programs. If future RCFGs are used, the type of variables is IProgramVarOrConst. IBoogieVar and IProgramVarOrConst are incompatible types, meaning that it is impossible to easily transform one to another.

In particular, it becomes currently impossible to transform an abstract state based on IBoogieVar into an abstract state using IProgramVarOrConst. If, however, all abstract states were using IProgramVarOrConst, one could use said state in both, RCFGs of the  future and "old" RCFGs.

Therefore, all IBoogieVar references should be made compatible to IProgramVarOrConst.

**Comment by danieldietsch** [comment]
We added the VARDECL generic to avoid casting -- how do you propose to avoid casting in the future?
