### ISSUE TITLE
Rename TraceChecker to TraceCheck

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#229]
The name TraceChecker is misleading. The name suggests that such an object (once constructed) can be used to check traces.
However, if the construction of the object is finished the object "only" represents the trace check and its public methods only allow you to get input, output and statistical information.

If no one objects I will to the renaming indicated by the title.

**Comment by danieldietsch** [comment]
I like it.

**Comment by greitsch** [comment]
No objection from me.

**Comment by alexandernutz** [comment]
dito

**Comment by Heizmann** [comment]
But I have not done this yet!?!

**Comment by danieldietsch** [comment]
But I did it with ee68654.

**Comment by Heizmann** [comment]
Thanks. But one should not only relabel the class name but also all variable names. I can do this if you think it is a waste of time.

**Comment by danieldietsch** [comment]
Oh, you are right. I forgot this, but can do it later.

**Comment by danieldietsch** [comment]
Should be finished with d92ef35 -- close if this is what you thought.

**Comment by Heizmann** [comment]
Thanks. I checked with 
`grep -ir cechecker trunk/source/*/src`
and did not find anything.
