### ISSUE TITLE
Compiling statically linked TPTP front-end

### ISSUE THREAD

**Issue by HanielB** [ultimate-pa/ultimate#230]
Hello,

I managed to compile the Z3 front-end for TPTP, but I would like to generate a statically linked binary of it. With the options "--staticbin" and "--staticlib" I generate a statically linked binary for Z3 itself, but that does not help me with the TPTP front-end.

Following suggestions from previous questions, I tried to manually add "-static" in LINK_FLAGS at the generated config.mk file, but that does not work. The TPTP front-end compilation complains that libz3.so is dynamically linked, and I did not manage to generate a static version of it...

Thanks

**Comment by greitsch** [comment]
Hello,

typically, *.so files are always dynamically linked libraries (so = shared object).

If you compiled z3 using the -static flag, there should also be a *.a file which is the statically linked file. Do you have such a file?

**Comment by HanielB** [comment]
Thanks for the quick reply.

Yes, I have this file. I'll try then to compile the TPTP front-end using this file instead of the libz3.so one!

(Sorry, I just now realize I created the issue in the wrong project...)

**Comment by greitsch** [comment]
I'm glad I could help. Good luck!
