### ISSUE TITLE
Bug in ThreeValuedEquivalenceRelation#projectToConstraintsWith

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#234]
While constructing seemingly a copy the above mentioned method in fact reuses data structure of the original.
I cannot understand its documentation but I guess the problem is a bug.

I did not want to change the original method (currently used in an evaluation) and added a new method ThreeValuedEquivalenceRelation#projectTo
https://github.com/ultimate-pa/ultimate/commit/68916df105b52361139540a942f908294818d64e

Please check and delete the old method in case the new method fixes the problem.

**Comment by danieldietsch** [comment]
I'd like to add that if some adds a method to a class he or she should add an author tag. I did nothing with ``ThreeValuedEquivalenceRelation#projectToConstraintsWith``, but perhaps @alexandernutz should take a look (the history indicates him as author).

**Comment by alexandernutz** [comment]
I agree with @Heizmann  that leads to sharing of an underlying Set between two ThreeValuedEquivalenceRelations.
However the new implementation does an additional intersection operation with the parameter set "elems" that is not intended.
I will update both the method and the documentation. 

(The intended purpose is to keep all constraints where at least one side is in the given Set<E> elems)

Can I delete the projectTo method after fixing projectToConstraintsWith? Eclipse shows me it is not referenced, but it has been wrong before..

**Comment by alexandernutz** [comment]
actually, I now believe it was not a bug -- at least the underlying sets were not shared.
The reason is that UnionFind#addEquivalenceClass makes a copy of its input set.
But I can see, that the code should make that clearer, so projectToConstraintsWith now makes a copy.

**Comment by Heizmann** [comment]
> Can I delete the projectTo method
No. I need this method and it was not nice to comment it.

**Comment by Heizmann** [comment]
> But I can see, that the code should make that clearer,

It would be good if you could also update the documentation. If one can understand the documentation it might also become clear what your method does.

**Comment by alexandernutz** [comment]
sorry. I updated both documentation and method name (commits linked above in this thread), dont you like them?

**Comment by Heizmann** [comment]
I did no knew that you also updated the documentation.
