### ISSUE TITLE
Terms that are use by model checkers have to be in a certain normal form

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#235]
We have the problem that we need expensive simplifications to get rid of simple redundancies.
E.g., we have terms of the form `(and (= x 0) (= x 0))` where the `0` in each conjunct is a different kind of term and hence simplification is non-trivial.

I am starting not to enforce a certain normal form (helps me for quantifier elimination).
https://github.com/ultimate-pa/ultimate/commit/c49ea7cb444256e1049aef824911836420f8783f
The rules will be documented in `UltimateNormalFormUtils` and become more strict in the next months. If you use our utility methods for the construction of terms you should be on the safe side.

**Comment by danieldietsch** [comment]
In this context: how do we want to check if Ultimate adheres to this normal form? 

One way would be a new Script, called e.g. ``UNFEnforcerScript``, that wraps existing ones and asserts the normalform in script.term(). We could then in ``SolverBuilder`` detect whether we are running with ``-ea`` or not and depending on the result, let the builder wrap new scripts with ``UNFEnforcerScript``.

**Comment by Heizmann** [comment]
Might be an option. Might not work.
* I think we have (or had?) somewhere some code that wants to know if the script is wrapped by a LoggingScript, this code (I don't like it) might not work if the LoggingScript itself is wrapped.
* Furthermore, I don't know yet how expensive these checks will become.
I don't want to think about this problem now.

**Comment by maul-esel** [comment]
The _Ultimate normal form_ has now existed for a few years and is enforced by the `SmtUtils` methods for creating terms. Hence I am closing this issue.
