### ISSUE TITLE
Behavior of Ultimate is nondeterministic on ICFGs whose edges are not CodeBlocks

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#237]
All ICFG edges but CodeBlocks to not implement hashCode() and equals() and as a consequence many algorithms do not behave deterministically.

We cannot simply implement  hashCode() and equals() for these classes in a naive way because one field is the Payload which does not provide deterministic hashCodes.

Options that we have
* Implement hashCode() and equals() for some classes and ignore the Payload.
* Add a serial number to ICFG edges. Always use a factory to construct them.

**Comment by danieldietsch** [comment]
I think the factory route may be the best option. I can go ahead and implement this.

**Comment by Heizmann** [comment]
I would appreciate that. Maybe I also have to use this factory in some places (e.g., construction of path programs?)

**Comment by danieldietsch** [comment]
Probably. I will look into it.
