### ISSUE TITLE
Bug in BlockEncoding

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#238]
BlockEncoding (incorrectly) removes all edges from a nonterminating program.

trunk/examples/settings/buchiAutomizer/ncsb/SUNFLOWER-ORIGINAL.epf
trunk/examples/programs/termination/RustlingRatsInTheNight.bpl
trunk/examples/toolchains/BuchiAutomizerBplWithBlockEncoding.xml

**Comment by danieldietsch** [comment]
This is due to an error in the settings: For non-termination, you should have ``/instance/de.uni_freiburg.informatik.ultimate.plugins.blockencoding/Remove\ sink\ states=false`` in the settings file
