### ISSUE TITLE
VpDomain is massively non-deterministic

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#240]
Various features of the ``VPDomain`` lead to non-determinism which in turn prevents effective debugging. 

The domain should behave as deterministic as possible. One naive way toward this goal is replacing all hashing data structures with ones that retain insertion order, e.g. ``HashSet`` to ``LinkedHashSet``.

**Comment by alexandernutz** [comment]
sha cf347a53936fb10e3cf0a3a2676d6ccc4afa8024 hopefully made things much more deterministic (deterministic hashCode for the elements in the CongruenceClosure objects)

**Comment by alexandernutz** [comment]
the observed nondeterminism should be gone through the addition of hashCode implementatiosn mentioned above, so I closed this issue, feel free to reopen if you observe nondeterminism again.
