### ISSUE TITLE
Another SMTInterpol Bug

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#248]
Input:svcomp/loops/eureka_05_true-unreach-call_true-termination.i Settings:settings/svcomp2017/automizer/svcomp-Reach-64bit-Automizer_Default.epf Toolchain:toolchains/AutomizerCInline.xml
			ExpectedResult: SAFE UltimateResult: EXCEPTION_OR_ERROR   [de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction: SMTLIBException: generated interpolants did not pass sanity check: de.uni_freiburg.informatik.ultimate.smtinterpol.smtlib2.SMTInterpol.getInterpolants(SMTInterpol.java:1000)]

**Comment by Heizmann** [comment]
Is this new bug or known problem?

**Comment by danieldietsch** [comment]
There are two open bugs in SMTInterpol that should be fixed soon. One of them is related to non-inductive interpolants. Without the script I cannot say if this bug is known.

**Comment by tanjaschindler** [comment]
Fixed this in SMTInterpol version 2.1-414-g9a9e052 (see update in Ultimate in 72ce512).
