### ISSUE TITLE
better array initialization in C to Boogie translation

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#259]
Improve the Boogie code that is generated from an array initialization in the C program (by default or via initializer).

Example:
int a[10][10][10] = {1, 2};
will be translated to 1000 boogie statements each one initializing one array cell. 998 of them initialize to 0.

Plan for initializing an array:
1. Set all cells to the default value. 
2. Update all cells that are explicitly mentioned by the initializer to the corresponding value

I believe we should improve step 1.
Several approaches come to mind:
 - use nested while loops in Boogie
 - use a special initialization function in Boogie that has an adequate specification (will need universal quantification)
 - use SMT default arrays (means that the RCFGBuilder is involved, too)

(I did not find a corresponding issue, let me know if this is a duplicate)

**Comment by alexandernutz** [comment]
A related issue is that we do not support initialization of variable length arrays with our current method. This should be dealt with by all three proposed approaches.

**Comment by alexandernutz** [comment]
If no one intervenes I will start by introducing a special function for array initialization. The first implementation of that function will be approach 1 (with while loops).

**Comment by danieldietsch** [comment]
We discussed that switching between the three approaches should be easy. Therefore I am all for implementing the one that is easiest right now.

**Comment by alexandernutz** [comment]
I am currently looking into this ticket. I think I know a way but it requires some changes to memory model and solver infrastructure that I want to discuss it here.

Situation:
 - It seems that our main use case are on-heap arrays, so I concentrate on them, here.
 - Example: Assume the following global C declaration: (It is global, so everything has to be initialized to 0.)
`int a[3];`
    we will generate Boogie code along these lines for this:
    ```
    #a := malloc(3 * sizeofInt);
    writeInt(0, {#a!base, 0 * sizeofInt});
    writeInt(0, {#a!base, 1 * sizeofInt});
    writeInt(0, {#a!base, 2 * sizeofInt});
    ```
    I would like to generate the following Boogie code instead:
    ```
    #a := malloc(3 * sizeofInt);
    #memory_int := #memory_int[#a!base := const-Array(0)]
    ```
   (i.e. inside the two-dimensional array `#memory_int`, I would like to assign a constant array to position `#a!base`)

What needs to be done:
1. Add support for the function `const-Array`
   This was discussed in #329, so conceptually I know which Boogie code to insert.
   However currently there is only a hack. (See `SolverBuilder#ENABLE_Z3_CONSTANT_ARRAYS`)
   I will need to do changes to the C translation (probably during declaration of memory model infrastructure) and in `SolverBuilder`.
   I have rough ideas how to do this, but comments and caveats are welcome.
2. Our current declaration of `#memory_int`, namely
`var #memory_int : [$Pointer$]int;` 
    is not compatible with the assignment as written above.
    The effective type of `#memory_int` is now `[int, int] int`, but for the assignment to work, we need `[int][int] int`.
    Any good ideas how this could be tackled? Or am I missing something?

**Comment by Heizmann** [comment]
> The effective type of `#memory_int` is now `[int, int] int`, but for the assignment to work, we need `[int][int] int`.

In my opinion, this is the main problem for the constant array optimization.

**Comment by Heizmann** [comment]
I think there is a misunderstanding.
I do NOT propose to replace `[int, int] int` by `[int][int] int`.

**Comment by Heizmann** [comment]
I would propose the following.
1. Find a way to refer to constant arrays in Boogie. This should be done by using/extending our [:builtin directive](https://github.com/ultimate-pa/ultimate/wiki/Boogie)
2. Develop (if necessary) a similar directive that allows us to translate a single function to a complex SMT term. Use some of the following ideas.
    A. Hardcode the SMT term in Ultimate (bad)
    B. Wrap the complex Term in an SMT function
    C. Hardcode the SMT function in Ultimate (bad)
    D. Obtain the SMT function as translation result of a Boogie function
    E. Define SMT-LIB functions like store, select in Boogie, use a special directive to prevent their translation.
    D. Pass the SMT-LIB function definition as an attribute (bad)
3. Develop (if necessary) a similar directive that is understood by the StructExpander and that makes sure that the attributes survive the preprocessor.

**Comment by danieldietsch** [comment]
I do not understand why there is a hack that already enables this functionality with z3 but no solution for the incompatible signatures. How does the hack work?

**Comment by alexandernutz** [comment]
Ok, here is my proposal after some offline discussions with @danieldietsch  and @jhoenicke :
I am not totally sure, which of @Heizmann 's  letters it corresponds to, if any. Perhaps B?

Solution for Problem 1:
 - I introduce a class called `SMTPrelude`. 
 - `SolverBuilder.buildAndInitializeSolver` takes an `SMTPrelude` object as an optional argument.
 - `SMTPrelude` contains SMT commands of the type `declare-fun` and `define-fun`
 - `SolverBuilder.buildAndInitializeSolver` enters the commands from `SMTPrelude` in the newly created script (as the hack did before)
 - I do not know yet, how easy or hard it is to pass an object from the CTranslation to the SolverBuilder. Hints are appreciated.

Solution for Problem 2:
 - move the problem of multidimensional vs nested arrays to the SMT-level, where there are only nested arrays
 - for every memory array, for example `mem_int : [Pointer] int` do the following,
    - add a Boogie function to the translated program
    ```function { :builtin initializeToZero_mem_int} (array : [Pointer] int, baseAddress : int);```
    - add the following command to SMTPrelude
    ```
    (define-fun initializeToZero_mem_int 
     ((array (Array Int (Array Int Int))) (baseAddress Int)) (Array Int (Array Int Int)) 
     (store array baseAddress ((as const (Array Int Int)) 0)))
    ```

Overall this seems to be the simplest solution to me. One benefit is that the current builtin directive should suffice and there have to be no Boogie infrastructure or the memory model of the translation.

**Comment by danieldietsch** [comment]
You can easily pass the prelude object via the toolchain storage. 
I would try and ensure that there is only one prelude object for a toolchain, so that if other plugins also want to add something, they add it to this object. 

One example for a toolchain storage is ``CodeBlockFactory``. It 
 * implements the ``IStorable`` interface
 * has the methods ``getFactory(IToolchainStorage)`` and ``storeFactory(IToolchainStorage)`` 

You can just replicate this pattern in the ``SMTPrelude`` object. 
If you want to allow multiple ``SMTPrelude`` instances, I would instead build an ``SMTPreludeStorage`` object that can hold these, and make the ``SMTPreludeStorage`` an ``IStorable``

**Comment by alexandernutz** [comment]
For the record: there is a certain ugly aspect of the current solution:

Say, we want to initialize an array of pointers. In Boogie, we will use this function:
```
function { :builtin "initToZero_Pointer" } init(a : [$Pointer$] $Pointer$, p : int) 
    returns (res : [$Pointer$] $Pointer$);
```
However, the BoogiePreprocessor will convert this function into the following two functions (because the return value is a struct):
```
function { :builtin "initToZero_Pointer" } init.base(a.base : [int,int]int, a.offset : [int,int]int, p : int) 
    returns (res : [int,int]int);
function { :builtin "initToZero_Pointer" } init.offset(a.base : [int,int]int, a.offset : [int,int]int, p : int) 
    returns (res : [int,int]int);
```

Now in our case this seems acceptable, because we can use the same smt function for both Boogie functions, but in general this does not seem very nice to me.

**Comment by danieldietsch** [comment]
Hm, I did not remember that. I thought that functions can also have multiple return parameters.

One fix could be to also allow pure procedures without implementation instead of the function. Also with the ``builtin`` attribute.

Then we would possibly get
````
procedure { :builtin "initToZero_Pointer" } init(a.base : [int,int]int, a.offset : [int,int]int, p : int) 
    returns (res.base : [int,int]int, res.offset : [int,int]int );
modifies()
````

**Comment by danieldietsch** [comment]
I also think having self-contained Boogie programs is important. 
But I think the problem does not change by much if we move the SMT prelude to the Boogie program. 

How do we create the term for ``:smtdefined`` ? 
 * Just a string, hardcoded somewhere
 * We create a term and use ``toStringDirect()`` (do we create a new script only for this or do we move the creation of the auxiliary solver to an earlier point in the toolchain?)  

How do we recover it from the Boogie code? 
 * With the [``TermParseUtils``](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/source/SMTSolverBridge/src/de/uni_freiburg/informatik/ultimate/smtsolver/external/TermParseUtils.java) we currently use in our unit tests
 * Optimization: During the translation we create an annotation for the function and if this annotation is present we use the term contained in it. 

What is the solution for struct return types? 
 * No one commented on my "lets use procedures without implementation instead" proposal. Is it a bad idea? Why? 
 * The only other idea I have is extending Boogie s.t. functions can have multiple return arguments (semantically a tuple)

 I can help with the Boogie and Boogie to SMT part.

**Comment by alexandernutz** [comment]
Regarding self-containedness:
The benefit I see is that we have a chance of recovering the semantics when the SMT code is in the Boogie program. In my previous proposal it would have been gone after dumping the program to a text file.

Regarding SMT type checking:
 - During translation to SMT is late but somewhat natural, and probably requires the fewest changes.
 - Whether there is type checking during creation of the Boogie program is of course left to the creator. We are doing partial type checks in the C to Boogie translation. We could also have a script there for SMT type checking (however, checking that the SMT term is compatible with the Boogie function's signature would require additional code). Imo this is not urgent and could be done later.

Regarding recovering from Boogie:
 - I agree: In general we will need an SMT paser here. `TermParseUtils` sounds like a good idea. Note that some matching of arguments probably needs to happen. I suppose the arguments are parsed as constants but might need to be variables, maybe some renaming has to happen.

Regarding struct return types:
The main problem seems to me that for a general solution we might want to have different SMT functions for each entry of the returned struct. So we would need an attribute that allows us to specify several SMT functions. Something like this:
```
function { :smtdefined "0" "p.offset" } resetbase(p : $Pointer$) 
    returns (res : $Pointer$);
```
(The example is just to get the idea across, I do not have a general solution. It might not be correct Boogie syntax either.)
`resetbase` would be the function that takes a pointer and returns a pointer whose base hase been set to 0 while the offset is left as is.
Our usecase looks even somewhat harder because the return type is ``[Pointer] Pointer``.
If anyone has a proposal or comments, please let me know.

**Comment by danieldietsch** [comment]
What is the issue with using procedures? Seems much more elegant.

**Comment by Heizmann** [comment]
> No one commented on my "lets use procedures without implementation instead" proposal. Is it a bad idea? Why?

I think that would work too, but I cannot see the problem that this solves.
In doubt, Functions seem to be more natural since functions may occur in expressions and in SMT-LIB functions also have only one return value.

Regarding the struct problem.
I think the proposed solution seems reasonable. An alternative might be to wrap the two annotations explicitly in an annotation that is a directive for the struct expander. Maybe only by using a different keyword that does explicitly mention the struct expander.

But I also have to say that I cannot overlook the whole situation at the moment. How many functions do we need?
* One that initializes a one-dimensional array with a given value (at the moment only for future use cases)
* One that initializes a two-dimensional array with a given value at a certain position

Do we need more functions?

**Comment by alexandernutz** [comment]
Functions that have use cases in the InitializationHandler:
 - initialize a heap cell at a base pointer: 
    - probably the most relevant case by far
    - we need one function for each memory array (assuming all memory arrays have a different type)
    - example for `#memory_int`:
     ```
     function { :smtdefined "(store in0 in1 ((as const (Array Int Int)) 0))" } 
      ~initToZeroAtPointerBaseAddress~int(in0 : [{ base : int, offset : int }]int, in1 : int) 
            returns (out : [{ base : int, offset : int }]int);
     ```
 - initialize an off heap array
    - The Boogie function represents a constant array of the right dimension filled with 0s. This constant array is then assigned to the to-be-initialized array variable. 
    - (Note that we translate nested C arrays to nested Boogie arrays, not multidimensional Boogie arrays.)
    - we need one function per to-be-initialized array type
    - Example for an array of type int x int -> int
    ```
    function { :smtdefined "((as const (Array Int (Array Int Int))) ((as const (Array Int Int)) 0))" } 
      ~const-array-int~int~int() returns (out : [int][int]int);
    ```

**Comment by danieldietsch** [comment]
Ok, after our talk a short reminder for myself. 

**New attribute ``:expand-struct "<struct-field-id>"``**  
* Will be consumed (removed) by the struct expander. 
* Only allowed for function applications where the return type is a struct 
* All attributes following the ``:expand-struct "<struct-field-id>"`` attribute until the next ``:expand-struct``attribute or no more attributes are attached to the function that is created for the struct field specified by ``<struct-field-id>``

**New attribute ``:smtdefined "<Term>"``**  
* Only allowed for function applications 
* ``function { :smtdefined "<Term>" } <FooId> (...) returns(...)``
* Will be handled somewhere in the RcfgBuilder
* Name of return parameter does not matter. 
* Signature (types and names of parameters, type of return value) must match 
* Creates an SMT function with name ``<FooId>`` that takes parameters with matching sorts as the Boogie function, is of sort matching the boogie type, and has ``<Term>`` as definition. 
* Example  
A function ``function { :smtdefined "(ite (< x y) y x)" } max(x:int, y:int) returns(out:int)`` creates a new SMT function symbol ``(define-fun max ((x Int) (y Int)) Int (ite (< x y) y x))``

**Comment by danieldietsch** [comment]
@alexandernutz the attributes should now work and transfer correctly.

**Comment by alexandernutz** [comment]
We have made some progress. Now, the C translation, the StructExpander, and Boogie2Smt should work correctly (according to a few manual tests).

Problem right now:
Quantifier elimination for arrays crashes during verification. This might be a job for @Heizmann :-)..

The error message:
> java.lang.AssertionError: var is still there: |v_#memory_int_15| term size 5
> 	at de.uni_freiburg.informatik.ultimate.modelcheckerutils.smt.Elim1Store.elim1(Elim1Store.java:452)

The term which it is trying to eliminate from:
`(= |#memory_int| (~initToZeroAtPointerBaseAddress~int |v_#memory_int_15| |main_~#a~0.base|))`

The problem can be reproduced as follows:
 - set hook "use constant arrays" in CTranslation settings (at the very bottom)
 - toolchain: AutomizerC.xml
 - program: `examples/CToBoogieTranslation/regression/variableInitialization_array_onedim_fixedlength_03.c`

**Comment by alexandernutz** [comment]
Update: to avoid the quantifiers from trace interpolation, I tried out settings using only SMTInterpol. 
In this case the assertion that checks inductiveness of interpolants fails. I don not know why, yet.

**Comment by danieldietsch** [comment]
@alexandernutz Can you dump a script for the SMTInterpol case? Perhaps this is a job for @jhoenicke and/or @tanjaschindler

**Comment by Heizmann** [comment]
@alexandernutz Could you add a test to the `QuantifierEliminationTest` class?

Proceed like the more recent tests and use `SmtUtils.checkSatTerm(...)` instead of constructing the formula manually.

**Comment by danieldietsch** [comment]
You mean ``TermParseUtils.parseTerm(...)`` right?

**Comment by alexandernutz** [comment]
@danieldietsch @jhoenicke @tanjaschindler  here you go, the below file produces 
`(error "generated interpolants did not pass sanity check")` when run SMTInterpol on it
[debug.zip](https://github.com/ultimate-pa/ultimate/files/2566974/debug.zip)

**Comment by Heizmann** [comment]
@alexandernutz in this class is a special new method for quantifier elimination that does not make sense to me. You were using that method. I modified that call.
https://github.com/ultimate-pa/ultimate/commit/c854ea4e6ba0faf6819f8844583af41d0f757886
Now the first test passes and the second test fails because the quantified variable is the argument of a function application. My partial quantifier elimination does not support that case. (And I am not willing to change that unless the change helps)

I think, if we would replace `~initToZeroAtPointerBaseAddress~int` by the function body, my partial quantifier elimination would eliminate the quantifier.
Question to @alexandernutz and @danieldietsch: Could we inline this (use defined) SMT function immediately?

**Comment by danieldietsch** [comment]
We could do it during the construction of the Icfg. But the backtranslation will be difficult. Do you have an idea how we could do it there? Then you could explain it to me and I can implement it.

**Comment by Heizmann** [comment]
I see, that is a problem. But I have no idea for the backtranslation.
I think we have to look at individual expressions that occur in practise and think about solutions.

**Comment by danieldietsch** [comment]
I updated SMTInterpol in 5d08986750682c75e39ad1f92180c9582722463d

**Comment by danieldietsch** [comment]
I think this feature is now implemented and all follow-ups should get their own ticket.
