### ISSUE TITLE
C translation cleanup: InferredType seems useless

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#260]
Check if the class and all its dependencies can be removed.

The subclasses of BoogieASTNode typically have constructors in two versions:
One where an IBoogieType is given, one where it is omitted.
The translation can always use the latter variant. The former variant should only be used by the BoogiePreprocessor, which does its own type inference.

**Comment by Heizmann** [comment]
Absolutely not!
Fixing type errors  which are only reported by the BoogiePreprocessor is a time-consuming task.
The C translation should provide IBoogieTypes wherever possible. On the long run we are going to check for type errors immediately.

On the long run, all expressions should be constructed by the `de.uni_freiburg.informatik.ultimate.boogie.ExpressionFactory`. This class will then do the type checking. Furthermore, this class will do the type inference for all non-identifier expressions. Hence a developer of the C translation only has to provide the IBoogieTypes for identifiers.

**Comment by alexandernutz** [comment]
I see. I like the ExpressionFactory!

However, I'm not yet convinced that the class InferredType is of any use for this task.
Right now, the BoogiePreprocessor does not use it at all (was that different in the past?), and the places of the C translation where it is used seem all very old to me. My impression (although unverified) is that the code using InferredType currently is more or less dead (at least in the sense that removing it would not change the translation result for any program).

Shouldn't the ExpressionFactory use the subclasses of BoogieType instead, like the BoogiePreprocessor does?

**Comment by alexandernutz** [comment]
To sum up:
 - I now see that we want IBoogieTypes in the C translation in the future.
 - When someone does that implementation work, he or she will deal with InferredType. (My impression is that it might be easiest to delete it and start from scratch, but that will be up to that person.)
