### ISSUE TITLE
Support checking for overflows with bitvector translation

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#270]
As discussed in the last meeting with @danieldietsch and @jhoenicke, there is a bug in the current Ultimate dev branch which is exposed when using **-tc**  AutomizerReach.xml  and **-s** [all-64bit-Automizer_Bitvector.epf](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/settings/all-64bit-Automizer_Bitvector.epf) on the [CyclicBuffer.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/programs/toy/showcase/CyclicBuffer.c) example program, leading to several errors of the form
```
 * Results from de.uni_freiburg.informatik.ultimate.boogie.preprocessor:
  - TypeErrorResult [Line: 25]: Type Error
    Type check failed for BinaryExpression[COMPLEQ,FunctionApplication[~bvadd32,[FunctionApplication[~zero_extendFrom8To32,[IdentifierExpression[~pos~3,<LOCAL,main>]]],BitvecLiteral[1,32]]],IntegerLiteral[2147483647]]
```

This also prevents ultimate from finding existing out of bounds access issues with the program. 

full command line: _~/ultimate/releaseScripts/default/UAutomizer-linux$_
`~/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate -tc ~/ultimate/releaseScripts/default/UAutomizer-linux/config/AutomizerReach.xml -s ~/ultimate/trunk/examples/settings/all-64bit-Automizer_Bitvector.epf -i ~/ultimate/trunk/examples/programs/toy/showcase/CyclicBuffer.c`
full log: [ultimate_cyclicbuffer_typerror13nov2017.log](https://github.com/ultimate-pa/ultimate/files/1468881/ultimate_cyclicbuffer_typerror13nov2017.log)

the following settings **do not** throw the relevant exceptions and work well (within their capabilities):
```
~/ultimate/trunk/examples/settings/default/automizer/svcomp-Reach-64bit-Automizer_Bitvector.epf
~/ultimate/trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-64bit-Automizer_Bitvector.epf
~/ultimate/trunk/examples/settings/default/automizer/svcomp-Overflow-32bit-Automizer_Default.epf
~/ultimate/trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf
```

Notably, running the affected **all-64bit-Automizer_Bitvector.epf** setting against other showcase example programs such as [McCarthy91.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/programs/toy/showcase/McCarthy91.c)  also consistently leads to _Type Error_ exceptions:
`~/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate -tc ~/ultimate/releaseScripts/default/UAutomizer-linux/config/AutomizerReach.xml -s ~/ultimate/trunk/examples/settings/all-64bit-Automizer_Bitvector.epf -i ~/ultimate/trunk/examples/programs/toy/showcase/McCarthy91.c`
```
[...]
 * Results from de.uni_freiburg.informatik.ultimate.boogie.preprocessor:
  - TypeErrorResult [Line: 17]: Type Error
    Type check failed for BinaryExpression[COMPLEQ,FunctionApplication[~bvsub32,[IdentifierExpression[~x,<LOCAL,f91>],BitvecLiteral[10,32]]],IntegerLiteral[2147483647]]
[...]
```

versions affected:
including newest 3fd13df4ed13bd6af11122ecb2df92246392c087 from Mon Nov 13 18:39:31 2017.

**Comment by danieldietsch** [comment]
The reason for this behavior is that overflow checks are currently incompatible with bit-precise translation. The fix will be two-fold: 
 * delete ``all-64bit-Automizer_Bitvector.epf`` and introduce ``all-64bit-Automizer_Default.epf``
 * explore bitvector translation for overflow settings

**Comment by invd** [comment]
With today's Ultimate version, this is still broken, although with different error output when compared to November.

`~/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate -tc ~/ultimate/releaseScripts/default/UAutomizer-linux/config/AutomizerReach.xml -s ~/ultimate/trunk/examples/settings/all-64bit-Automizer_Bitvector.epf -i ~/ultimate/trunk/examples/programs/toy/showcase/CyclicBuffer.c`
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: TypeCheckException: Type check failed for C: pos + 1 [25]
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: TypeCheckException: Type check failed for C: pos + 1 [25]: de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:52)
```

**Comment by invd** [comment]
This issue is still present 0.1.23-97aecd6:
```
[2018-07-31 16:24:15,959 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
de.uni_freiburg.informatik.ultimate.boogie.typechecker.TypeCheckException: Type check failed for C: pos + 1 [25]
        at de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:52)
```

**Comment by invd** [comment]
This is still present in Ultimate 51a90dfc485d834f02fe0076b0db00e26a2aff06.

CyclicBuffer.c:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: TypeCheckException: Type check failed for C: pos + 1 [25]
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: TypeCheckException: Type check failed for C: pos + 1 [25]: de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:52)
```

McCarthy91.c:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: TypeCheckException: Type check failed for C: x -10 [17]
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: TypeCheckException: Type check failed for C: x -10 [17]: de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:52)
```

**Comment by invd** [comment]
The error is still present in cf7845638a016090978a13501adca3f0b2bbcea4, which means it is now reported for over a year.

**Comment by schuessf** [comment]
Support was added in ff96da4e576f0a4a144eadb941dd5e7d137757c5
