### ISSUE TITLE
Fix NPE

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#274]
26 benchmarks affected; ``de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: java.util.ArrayDeque.<init>(ArrayDeque.java:212)``

Minimal example in following commit

**Comment by alexandernutz** [comment]
Seems like we translate this correctly now. (probably treatment of conditional operator was the problem.)
