### ISSUE TITLE
Fix NPE in constructStructFieldInfos

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#275]
10 benchmarks affected by ``de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.InitializationHandlerInitializerInfo.constructStructFieldInitInfos(InitializationHandler.java:911)``

Minimal example in follow-up commit

**Comment by alexandernutz** [comment]
should be fixed by SHA 1a7e5f7611c96c11eccce0f0822298e79fbaa4ba
