### ISSUE TITLE
Add parent pointers to ACSL AST

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#282]
For the Multiparse symboltable we want (need) parent pointers in ACSL ASTs. This allows us to dynamically look up the scope for quantifier expressions (similar to the dynamic scope lookup in IAST-based structures)

**Comment by danieldietsch** [comment]
@buehlery : Do we still need these parent pointers? Or can we close the ticket and use the current solution?

**Comment by buehlery** [comment]
@danieldietsch : They are no longer needed, the problem was solved by storing a C-AST node which acts as the parent of the currently dispatched ACSL node(s).

**Comment by danieldietsch** [comment]
Optimal!
