### ISSUE TITLE
Support checks for unsigned overflows

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#29]
As the title suggests: We want to be able to check for unsigned overflows.

**Comment by alexandernutz** [comment]
adressed in commits
74fab2a87176ce8e9b7cbf5612a778566a516228
4678bc618bcfa331635907bbe037e09d2edfb152

unsigned over-/underflow checks can be activated by setting the option in the C+ACSL Translation preference page named "how to treat unsigned ints differently from normal ones" to ASSERT.
(the option might be renamed to "how to treat unsigned ints" in the near future)
