### ISSUE TITLE
IllegalArgumentException: only call this for non-varlength array types

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#292]
Problem: 
"IllegalArgumentException: only call this for non-varlength array types" during translation.

 * Minimized input: 
[ctrans-bug-min-IAE-only-nonvarlength.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-min-IAE-only-nonvarlength.c)
 * Settings: ``settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf``
 * Toolchain: ``toolchains/CheckedCTranslation.xml`` (or any Automizer toolchain) 

This issue occurred during analysis of Trezor firmware and is blocking progress there.

**Comment by invd** [comment]
I can confirm that 0.1.23-c168100 no longer has issues for ctrans-bug-min-IAE-only-nonvarlength.c when run with AutomizerMemDerefMemtrack.xml + svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf.
