### ISSUE TITLE
IllegalArgumentException: RValues cannot have array type

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#293]
Problem: 
"IllegalArgumentException: RValues cannot have array type" during translation.

 * Minimized input: 
[ctrans-bug-min-RValues-cannot-have-array-type-string-tertiary-op.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-min-RValues-cannot-have-array-type-string-tertiary-op.c)
 * Settings: ``settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf``
 * Toolchain: ``toolchains/CheckedCTranslation.xml`` (or any Automizer toolchain) 

This issue occurred during analysis of Trezor firmware and is blocking progress there.

**Comment by invd** [comment]
@alexandernutz: unfortunately, this issue does not seem completely solved to me for the provided example code.

Error output with a freshly built Ultimate 0.1.23-bf6525c and AutomizerMemDerefMemtrack.xml + svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf settings: 
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: TypeCheckException: Type mismatch ([int]int != { base:int, offset:int }) in C: 0 ? "" : 0 [3]
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: TypeCheckException: Type mismatch ([int]int != { base:int, offset:int }) in C: 0 ? "" : 0 [3]: de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:19)
```

When running said Ultimate configuration on the original, non-minified program: 
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: AssertionError: implement if needed
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: AssertionError: implement if needed: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.BoogieTypeHelper.getBoogieTypeForCType(BoogieTypeHelper.java:119)
```

Is it reasonable to reopen this issue?

**Comment by alexandernutz** [comment]
huh.. well, seems like a fix for something else broke this fix -- I'll look into it.

**Comment by invd** [comment]
I can confirm that 0.1.23-626ba71 solves the "TypeCheckException: Type mismatch" issue.

The original program with 5000+ lines of code still throws the "AssertionError: implement if needed" exception, but I suspect this is not directly related to this issue, and I will bring it up in a separate ticket.

**Comment by alexandernutz** [comment]
..great! minimized programs are nice, also for documentation and regressions. -- if minimization is hard however, and the problem is reproducible in reasonable time, you can also link a bigger program in an issue, or do a partial minimization only..
