### ISSUE TITLE
TypeError due to multidimensional array to pointer cast

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#294]
Problem: 
````
TypeErrorResult [Line: 7]: Type Error
    Wrong parameter type at index 2: CallStatement[false,[],data2hex,[BitvecLiteral[0,32],BitvecLiteral[0,32],ArrayAccessExpression[IdentifierExpression[~str~2,<LOCAL,layoutFirmwareHash>],[BitvecLiteral[0,32]]]]]
````
during preprocessing.

 * Minimized input: 
[ctrans-bug-min-TE-multidim_char_array.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-min-TE-multidim_char_array.c)
 * Settings: ``settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf``
 * Toolchain: ``toolchains/AutomizerC.xml`` (or any toolchain with translation and preprocessing)

This issue occurred during analysis of Trezor firmware and is blocking progress there.

**Comment by invd** [comment]
I can confirm that 0.1.23-c168100 **no longer shows issues** for the minified example code.

Test settings:
*  AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf
