### ISSUE TITLE
Fix Jenkins mails

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#296]
Jenkins should notify users about regression test failures.

The idea is that if there are test regressions in the nightly build, every commiter since the last nightly build should receive a ``Test Regression`` mail.

**Comment by greitsch** [comment]
Both, the server and Jenkins are able to send mails. I don't know what the problem is.

**Comment by greitsch** [comment]
Tested in builds 28d396fba548b993f8a5c261860f7342ada06984 and 25327ba9f53dc1673ba0565aa311eb80cb11711c . Mails were sent.

**Comment by danieldietsch** [comment]
The problem is not yet fixed

**Comment by danieldietsch** [comment]
It seems that my config change fixed this.
