### ISSUE TITLE
Jenkins Error for Distress

### ISSUE THREAD

**Issue by greitsch** [ultimate-pa/ultimate#297]
During an update, Jenkins complains about unreadable data associated to the Distress project:

ConversionException: Refusing to unmarshal parsedVersion for security reasons; see https://jenkins.io/redirect/class-filter/ ---- Debugging information ---- class : org.apache.maven.artifact.versioning.DefaultArtifactVersion required-type : org.apache.maven.artifact.versioning.DefaultArtifactVersion converter-type : hudson.util.XStream2$BlacklistedTypesConverter path : /maven2/dependencies/dependency/parsedVersion line number : 25 -------------------------------

cf. https://monteverdi.informatik.uni-freiburg.de/ci/administrativeMonitor/OldData/manage

I did not discard the message yet, because I don't know whether this may affect the Distress build.

**Comment by danieldietsch** [comment]
Data can be discarded without issue.
