### ISSUE TITLE
 NullPointerException: null: java.util.ArrayDeque.<init>(ArrayDeque.java:217)

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#299]
Problem:
`- ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: java.util.ArrayDeque.<init>(ArrayDeque.java:217)`
during translation.

- Minified input: 
[ctrans-bug-min-TE-emptyarray-nullpointer-arraydeque.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-min-TE-emptyarray-nullpointer-arraydeque.c) 
**Please note that this input is not C standard compliant.** For more information, see the posts below.
- Settings: `settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf`
- Toolchain: `UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml`

This issue occurred during analysis of Trezor firmware, but is only loosely relevant to progress there.

**Comment by alexandernutz** [comment]
We have at least two issues with this code:
 - zero-length array
 - empty initializer

zero-length (fixed size) arrays are a gcc feature:
https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html
 so we should support them. (todo..)

Question:
should we support empty initializers? gcc does not accept them when called with the --pedantic switch.
@invd  : is the empty initializer perhaps an artifact from minimization?

**Comment by invd** [comment]
@alexandernutz: this behavior was found during manual minimization of issue #298. 
This specific type of error does not occur in Ultimate when run against the original target code and is therefore not directly relevant to our ability to verify the original code, unlike issue #298.

I agree that this is a special edge case and that the code does not fully conform to the C standard(s) and is therefore low-priority. This was also discussed with @danieldietsch and @jhoenicke during the meeting. I have updated the initial post to reflect this.
However, the point can be made that Ultimate should at least gracefully fail upon such input and hardening the ArrayDeque class against such NullPointerExceptions might help with other error paths as well. 

GCC 6.3.0 does not warn against the zero-size array or empty initializer braces when used without "--pedantic", therefore it is plausible that Ultimate might see this in broken production code.

With "--pedantic":
```
warning: ISO C forbids zero-size array ‘pubkey’ [-Wpedantic]
warning: ISO C forbids empty initializer braces [-Wpedantic] 
```

Regarding the zero-length array: Ultimate appears to work correctly when line no.5 is replaced by
`static const uint8_t * const pubkey[0];`

```
[...]
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction:
  - CounterExampleResult [Line: 8]: array index can be out of bounds
    array index can be out of bounds
We found a FailurePath:
[L8]        pubkey[0]
```

**Comment by invd** [comment]
@alexandernutz: the Jenkins test system on monteverdi still counts the current "Incorrect Syntax" exception on the regression program mentioned above as a [failure](https://monteverdi.informatik.uni-freiburg.de/ci/job/Ultimate%20Nightly/lastBuild/de.uni_freiburg.informatik.ultimate$de.uni_freiburg.informatik.ultimate.regressiontest/testReport/de.uni_freiburg.informatik.ultimate.regressiontest.translation/C2BoogieRegressionTestSuite/cToBoogie_xml_cToBoogie_Default_Reach_epf___storage_jenkins_jenkins_home_jobs_Ultimate_Nightly_workspace_trunk_examples_CToBoogieTranslation_regression_ctrans_bug_min_TE_emptyarray_nullpointer_arraydeque_c/). Is there a marking mechanism such as `//#Safe` that encodes cases where Ultimate is expected to throw an exception?

**Comment by invd** [comment]
@danieldietsch: Jenkins still counts the valid "Syntax Error" response by Ultimate as an error. How to encode this expected result in the regression?

**Comment by danieldietsch** [comment]
Currently, there is no easy way. We need a separate test result decider for that. 
I have a ticket draft for an improved regression test environment where this will be possible. 

Perhaps an intermediate step could be to have a richer syntax for expected values in files.

**Comment by invd** [comment]
From my point of view, it could be reasonable to put this "noncompliant" C code example into a special subdirectory that is exempted from regular regression testing until the test outputs can be interpreted correctly. Having constant invalid test results lowers the willingness of developers to look at them, and of those 261, there are likely a few that require attention.
