### ISSUE TITLE
more expressive toString() implementation for Summary

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#300]
current state:
		return "SUMMARY";

For ease of debugging I would propose for example
		return "SUMMARY " + mPrettyPrintedStatements;

this will print the call statement

advantages:
 - one can tell different Summary objects appart in a set
 - somewhat consisten with other CodeBlock's toString() (which prints the statements of the CodeBlock)

any objections?

**Comment by Heizmann** [comment]
Maybe let's use 
``"SUMMARY  for " + mPrettyPrintedStatements``

In order to reduce ambiguity it might be helpful to also include the location before the corresponding return.

**Comment by alexandernutz** [comment]
thanks for the suggestion, 
hm, there is not always a corresponding return (if the method has no implementation) what should we add then?
(actually I only read your suggestion well enough after doing the commit, sorry) 
I went for
		return "SUMMARY for " + mPrettyPrintedStatements + " srcloc: " + mSource;
for now.
I can change it again if anyone wants further improvements
