### ISSUE TITLE
Results are incorrectly marked with [Line: 1]

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#303]
During verification of C files **with** and **without** gcc-provided '#line' directives, many cases of incorrect "[Line: 1]" result outputs have been observed by me and verified by @danieldietsch and @jhoenicke. 
As it has been suggested that this behavior could be triggered by more than one specific bug, this ticket is dedicated to the general "Line: 1" error pattern.

In my understanding, Ultimate should print [Line: **-1**] if the exact location has not been set and [Line: X]  with X as a valid line number in any other case. 
@danieldietsch has mentioned that the current behavior is likely caused by erroneously initialized check-annotations. 

Example for such result messages:
```
- UnprovableResult [Line: 1]: Unable to prove that pointer dereference always succeeds
    Unable to prove that pointer dereference always succeeds
```
```
- PositiveResult [Line: 1]: pointer dereference always succeeds
  For all program executions holds that pointer dereference always succeeds at this location
```
```
- CounterExampleResult [Line: 1]: pointer dereference may fail
  pointer dereference may fail
We found a FailurePath:
[...]
```

It's obvious that wrongly attributed error locations obscure the actual errors and make Ultimate much harder to use.

**Comment by alexandernutz** [comment]
could you point to one or more example files where this happens?

**Comment by invd** [comment]
@alexandernutz: I have prepared a minified example:
```
#include <stdint.h>

// Ultimate needs this
typedef unsigned int uint32_t;

int main(void)
{
  uint32_t data = (*(volatile uint32_t *)(0x50000000U));
  return 0;
}
```

This will produce a CounterExampleResult in under 10 seconds:
```
  - CounterExampleResult [Line: 1]: pointer dereference may fail
    pointer dereference may fail
We found a FailurePath:
```

Toolchain: _releaseScripts/default/UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml_

Settings tested:
* _trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf_
* _trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf_

Ultimate: 0.1.23-99a7257 (newest)

**Comment by alexandernutz** [comment]
looks great, thanks!
I am currently changing the C translation in many places (branch wip/nutz/expressionfactory), I'll try to come up with something that can be merged back very soon. Then I'll look into the problem (if it persists..).

**Comment by invd** [comment]
In addition to results incorrectly marked with ```[Line: 1]```, there have been a few occurrences of results attributed to ```[Line: -1]```, which is more consistent, but still not very helpful, and also hints at related coding errors in Ultimate.

I have been successful in tracking down and minimizing one of the relevant code positions generating both the  **Line 1** as well as the **Line -1** statement:

```
#include <stdint.h>
// memset definition to satisfy gcc --pedantic
#include <string.h>

typedef unsigned char uint8_t;

static uint8_t _oledbuffer[8];

int main()
{
  memset(_oledbuffer, 0, sizeof(_oledbuffer));
  return 0;
}
```

```
  - PositiveResult [Line: 1]: pointer dereference always succeeds
    For all program executions holds that pointer dereference always succeeds at this location
  - StatisticsResult: Ultimate Automizer benchmark data for error location: ULTIMATE.initErr1RequiresViolation
[...]
 - PositiveResult [Line: -1]: pointer dereference always succeeds
    For all program executions holds that pointer dereference always succeeds at this location
  - StatisticsResult: Ultimate Automizer benchmark data for error location: mainErr1RequiresViolation
[...]
  - PositiveResult [Line: 9]: all allocated memory was freed
    For all program executions holds that all allocated memory was freed at this location
  - StatisticsResult: Ultimate Automizer benchmark data for error location: mainErr2EnsuresViolation
[...]
  - PositiveResult [Line: -1]: pointer dereference always succeeds
    For all program executions holds that pointer dereference always succeeds at this location
  - StatisticsResult: Ultimate Automizer benchmark data for error location: mainErr0RequiresViolation
```

Runtime configuration:
 * Ultimate 0.1.23-99a7257
 * Toolchain: releaseScripts/default/UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml
 * Settings: trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf
 * Additional settings --traceabstraction.stop.after.first.violation.was.found false

Notably, setting the traceabstraction-flag to false makes the output more verbose, but this is not necessary to observe the described "Line"-behavior itself.

The corresponding example program will be uploaded later.

**Comment by danieldietsch** [comment]
@invd : my latest change fixed your example. If you like you can try to re-run, I am still waiting on regressions.

**Comment by invd** [comment]
@danieldietsch: there appears to be a regression for ```trunk/examples/CToBoogieTranslation/trezor/memset_example_9.c```
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: TypeCheckException: Type check failed for
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: TypeCheckException: Type check failed for : de.uni_freiburg.informatik.ultimate.boogie.TypeErrorReporter.report(TypeErrorReporter.java:19)
```
Settings:
* AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf

The first code example ```trunk/examples/CToBoogieTranslation/trezor/303-incorrectly_marked_w_line1_01.c``` runs fine and shows that "Line"-markings have indeed improved drastically, as correct lines are used:
```
  - CounterExampleResult [Line: 8]: pointer dereference may fail
    pointer dereference may fail
We found a FailurePath:
```

**Comment by danieldietsch** [comment]
@invd : Indeed there were regressions, but not in the file you referenced. I think this ticket should be fine for now.

**Comment by invd** [comment]
I can confirm that newer versions no longer show the TypeCheckException, and that I have not seen "Line 1" markings so far. I will check some larger programs once some of the other regressions are ironed out.

**Comment by invd** [comment]
As some of the regressions are already fixed, I was able to run Ultimate over one of the original programs that prompted this issue. 

The line markings now look much more reasonable:
```
      2   - PositiveResult [Line: 1956]: pointer dereference always succeeds
      4   - PositiveResult [Line: 1972]: pointer dereference always succeeds
      4   - PositiveResult [Line: 1978]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2335]: pointer dereference always succeeds
      6   - PositiveResult [Line: 2487]: pointer dereference always succeeds
   2048   - PositiveResult [Line: 2509]: pointer dereference always succeeds
      4   - PositiveResult [Line: 2521]: pointer dereference always succeeds
      4   - PositiveResult [Line: 2532]: pointer dereference always succeeds
      4   - PositiveResult [Line: 2543]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2554]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2556]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2557]: pointer dereference always succeeds
     50   - PositiveResult [Line: 2565]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2618]: pointer dereference always succeeds
      6   - PositiveResult [Line: 2634]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2689]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2717]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2718]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2730]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2731]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2753]: pointer dereference always succeeds
      2   - PositiveResult [Line: 2754]: pointer dereference always succeeds
      6   - PositiveResult [Line: 2755]: pointer dereference always succeeds
      2   - PositiveResult [Line: 3010]: pointer dereference always succeeds
      2   - PositiveResult [Line: 3017]: pointer dereference always succeeds
      1   - PositiveResult [Line: 3055]: all allocated memory was freed
      2   - PositiveResult [Line: 3488]: pointer dereference always succeeds
      2   - PositiveResult [Line: 3489]: pointer dereference always succeeds
      2   - PositiveResult [Line: 3490]: pointer dereference always succeeds
      2   - PositiveResult [Line: 3491]: pointer dereference always succeeds
      4   - PositiveResult [Line: 3496]: pointer dereference always succeeds
      1   - PositiveResult [Line: 3507]: array index is always in bounds
      1   - PositiveResult [Line: 3510]: array index is always in bounds
      1   - PositiveResult [Line: 3513]: array index is always in bounds
      1   - PositiveResult [Line: 5040]: array index is always in bounds
      2   - PositiveResult [Line: 5040]: pointer dereference always succeeds
      2   - PositiveResult [Line: 905]: pointer dereference always succeeds
      2   - PositiveResult [Line: 906]: pointer dereference always succeeds
      2   - UnprovableResult [Line: 1956]: Unable to prove that pointer dereference always succeeds
```
Some notes:
The concentration on line 2509 is explained in #308.

The "UnprovableResult" pointer dereference in line 1956 is this line of code:
```(*(volatile uint32_t *)((((0xE0000000U) + 0xE000) + 0x0D00) + 0x14)) |= (1 << 9);```
Reasons given by Ultimate:
 ```
Unable to prove that pointer dereference always succeeds
 Reason: overapproximation of large string literal at line 3477, overapproximation of bitwiseOr at line 2634.
```
