### ISSUE TITLE
BoogieType vs InferredType

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#304]
(I thought there was an issue related to InferredType already but cannot find it)

We want as much Boogie type checking as we can get already during C to Boogie translation; right now, many Boogie type errors are only detected by the BoogiePreprocessor.

However the class that was designed for this, InferredType, has not been maintained and is in poor condition.

BoogieType would be much more adequate for type checking purposes in my opinion.
However it is currently in the BoogiePreprocessor package.

Proposal:
Move BoogieType somewhere where the C to Boogie translation can see it. Delete InferredType.

What would be a good location for BoogieType and its descendants?

**Comment by Heizmann** [comment]
Good idea.
I think a "BoogieType" packge in Library-BoogieAST would be a good place.

**Comment by danieldietsch** [comment]
I agree

**Comment by alexandernutz** [comment]
thanks for the quick answers! This issue will be closed by one of my still unpushed commits.
