### ISSUE TITLE
ExpressionFactory Roadmap

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#305]
State of the ExpressionFactory:
 - inherits from BoogieTransformer, which is a "class to recursively walk through a Boogie tree, doing transformations.", according to the comments.
 - contains only static methods that mostly follow the pattern "construct and return an expression given some subexpressions"

Alleged purpose of the ExpressionFactory (please correct me if I am wrong):
 Build Boogie Expressions (and possibly statements and declarations) through it instead of using the constructors directly.
This enables on-the-fly type checking (and more?).

Questions:
What was the intention of inheriting from BoogieTransformer?

Would it be ok, to make the methods non-static? 
Reason: To return a SyntaxErrorResult one needs the Ultimate services and the Activator-pluginId. 
This would lead to changes wherever the methods were called of course. We would have to keep one more helper object around in the C to Boogie translation.

**Comment by danieldietsch** [comment]
After looking at the class I would say: 
  * It should not inherit from ``BoogieTransformer`` -- it does not use any of the super methods 
  * Its purpose is to perform some simplifications on Boogie expressions 
  * We should use it in more places, i.e., it should stay where it is. 
  * It should not report results by itself, but rather throw some kind of type checking exception 
  * The methods should stay static (or at least, your reason is not reason enough to make it non-static)
  * A result reporting wrapper would be nice

**Comment by Heizmann** [comment]
I mainly agree with Daniel but want to add that it should *not* do major simplifications and I am sceptical if the result reporting wrapper is necessary.
The *type checking exception* will only be thrown if an Ultimate programmer did a mistake. This class should not be used to type check user input.

The question whether the methods can stay static is however more difficult. Do we want to support to support type synonyms?
Some options
1. Omit type checking if named type is used (would not detect pointer vs. int bugs that we sometimes have)
2. Pass map with type synonyms in the method call
3. Pass map with type synonyms in constructor

I think, I would prefer Option 2.

**Comment by Heizmann** [comment]
One more comment.
I think we should not use this class for user provided Boogie programs since we do not have a backtranslation for these optimizations.

**Comment by alexandernutz** [comment]
I like Option 1. Currently BoogieType's descendants do not contain a named type anyway.
(In case you are wondering: BoogieASTType does have named types, but that is only used during parsing.)

If some day I should add an argument at the call sites of the ExpressionFactory methods, I would prefer it to be something extensible (we sometimes use the MainDispatcher for handing a link to all Handlers such, but a better solution would be nice..).

The main consequence of all this for the rest of the translation that I can see is that whenever an IdentifierExpression/VariableLHS is created, one has to give a type for it. Seems doable to me...

For the moment i will just throw an Exception, so I don't have to change anything at the call sites at the moment (which is consistent with Option 1).

**Comment by alexandernutz** [comment]
(just documenting the current state, no questions, so no need to read this if you're in a hurry)

I merged back the branch wip/nutz/expressionfactory yesterday. 
Current state with respect to this ticket: 
 - for every subtype of Expression, one should not use a constructor for creating an instance, but instead use the corresponding method in ExpressionFactory
 - these methods do not take a BoogieType but will construct it from the given subexpressions; exceptions: IdentifierExpression and VariableLHS, here, the methods also take a BoogieType
 - the ExpressionFactory determines types using methods in TypeCheckHelper; TypeCheckHelper essentially contains the type inference code from BoogiePreprocessor's TypeChecker (which now also uses TypeCheckHelper)
 - during preruns we sometimes have to circumvent the type inference by manually changing the BoogieType of an Expression, however that should never be done with Expressions that will end up in the translated program (it would directly result in type errors in the BoogiePreprocessor)
 - still open: some expressions are given an error type, right now, because it was not clear how to determine their BoogieType during creation. (in particular the BitVector case is concerned I think)

**Comment by alexandernutz** [comment]
After some more debugging the changes outlined above should be implemented and e.g. Boogie type checking during translation should work. --> closing this
