### ISSUE TITLE
Regressions: AssertionError getBoogieTypeForCType, ClassCastException CNamed cast

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#311]
This is another regression introduced during recent code changes and it prevents Ultimate from running on the Trezor codebase.

```
[2018-02-27 14:20:05,978 FATAL L292        ToolchainWalker]: The Plugin de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator has thrown an exception:
java.lang.AssertionError: implement if needed
        at de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.BoogieTypeHelper.getBoogieTypeForCType(BoogieTypeHelper.java:119)
```

Another regression on a modified version of the program in question:
```
* Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: ClassCastException: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CNamed cannot be cast to de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CPrimitive
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: ClassCastException: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CNamed cannot be cast to de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.container.c.CPrimitive: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.expressiontranslation.IntegerTranslation.addAssumeValueInRangeStatements(IntegerTranslation.java:668)
```

known to be affected: Ultimate 0.1.23-79e0a14
versions  without the regression:
* Ultimate 0.1.23-bc1c7a9 (first error)
* Ultimate 0.1.23-99a7257 (second error)

Settings:
* AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf

**Comment by alexandernutz** [comment]
this might be easily fixable, but I will need a code snippet, or a file or something like that to locate the error

**Comment by invd** [comment]
@alexandernutz: I will provide examples where possible, but that takes time.

Minimized example for the ClassCastException:
[ctrans-ClassCastException-CNamed-Cprimitive.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/ctrans-ClassCastException-CNamed-Cprimitive.c)
```
#include <stdint.h>

typedef unsigned int uint32_t;

uint32_t __stack_chk_guard;

uint32_t random32(void)
{
  // xkcd classic
  return 4;
}

int main(void)
{
  __stack_chk_guard = random32();
}
```

**Comment by invd** [comment]
@alexandernutz: the following example triggers the AssertionError:
[ctrans-ClassCastException-CNamed-Cprimitive.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/ctrans-ClassCastException-CNamed-Cprimitive.c)

```
enum rcc_periph_clken {
 RCC_OTGFS = (((0x34) << 5) + (7)),
};

void rcc_periph_clock_enable(enum rcc_periph_clken clken);

int main(void)
{
  rcc_periph_clock_enable(RCC_OTGFS);
}
```

Note, however, that gcc is not happy with this example: ```undefined reference to `rcc_periph_clock_enable'```.  Please treat this example program as unfinished.

**Comment by alexandernutz** [comment]
cool -- thanks!

It's not that important that they are minimized. I can try to fix it so it compiles..

**Comment by invd** [comment]
With Ultimate 0.1.23-49c3f53, both regressions appear to be solved for the examples as well as the original code files. Good work!
