### ISSUE TITLE
NullPointerException: CHandler.visit()

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#312]
This recently introduced regression is encountered upon running the preprocessed version of [soundness_fprintf_2.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/soundness_fprintf_2.c), which is one of the error examples from ticket #306.

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - ExceptionOrErrorResult: NullPointerException: null
    de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: NullPointerException: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.CHandler.visit(CHandler.java:1924)
```

Versions affected: including Ultimate 0.1.23-49c3f53

Settings:
* AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf

**Comment by danieldietsch** [comment]
We do not support streams at the moment, so ``fprintf`` is also not supported, except as uninterpreted function. 

The example in its current form dies because we cannot resolve the FILE type. It seems that it is no longer a NPE.

**Comment by invd** [comment]
There is another CHandler.visit NPE occurence that is triggered by the Trezor bootloader code, but the circumstances are complex, involving `vector_table->reset();` and Ultimate does only run into the NPE when certain USB callbacks are defined elsewhere in the file.
@danieldietsch: I will send you the original file directly.

**Comment by invd** [comment]
As Ultimate 0.1.23-809e8b6 detects the unsupported var args function call of the preprocessed fprintf example linked above, further parsing is refused and the original NPE is not observed.
The second occurrence of this bug is complex and cannot be minified in the foreseeable future.

**Comment by invd** [comment]
The **unprocessed** soundness_fprintf_2.c triggers another distinct NullPointerException as described in #306.

Running Ultimate on the **preprocessed** version of soundness_fprintf_2.c leads to the (intended) Unsupported Syntax exception, which prevents further testing of the NPE listed above.

Likely, this issue can be closed.
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - UnsupportedSyntaxResult [Line: 863]: Unsupported Syntax
    encountered a call to a var args function, var args are not supported at the moment
```
