### ISSUE TITLE
Soundness issue for out of bounds array access

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#313]
A recent change appears to break Ultimate's ability to check for out of bounds accesses in programs such as the following:

[memset_example_10.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/memset_example_10.c)
```
#include <stdint.h>

typedef unsigned char uint8_t;

static uint8_t _oledbuffer[1024];

int main()
{
  _oledbuffer[-1] = 0;
  return 0;
}
```

Relevant output:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction:
  - AllSpecificationsHoldResult: All specifications hold
    We were not able to verify any specifiation because the program does not contain any specification.
RESULT: Ultimate proved your program to be correct!
```

This is likely a regression that was introduced today and is easily revertible.

Version affected: Ultimate 0.1.23-49c3f53

Settings:
* AutomizerMemDerefMemtrack.xml 
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf

**Comment by danieldietsch** [comment]
Cannot reproduce, issue not present anymore.

**Comment by invd** [comment]
I have picked the wrong settings, which had no array access checks. Therefore, this issue is invalid and should be ignored.
