### ISSUE TITLE
Soundness issue: memory access for strings containing string literals

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#316]
In the program referenced in issue #298, a string-like structure is used to store a number of uint8_t elements representing a public key, which are given in the ascii-printable hexadecimal string literal format. Regular C programs treat those string literals as single-byte elements in memory, plus one terminating nullbyte for the string.
To demonstrate this:
`strlen("\x42")` == **1**
`sizeof("\x42")` == **2**

Ultimate has issues correctly decoding the value of such elements, as shown in #307. However, during recent boogie-related issues #314 and #315, we have observed that Ultimate treats also miscalculates the in-memory size of such structures, namely it ignores the special string literal role and reserves one byte for each of the ascii characters, plus terminating nullbyte.

In the [ctrans-bug-min-TE-static-const-uint8_t.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/regression/ctrans-bug-min-TE-static-const-uint8_t.c) example, the 65+1 bytes are miscalculated as 4*65+1=**261** bytes, and all checks are performed on that:

```
    call #t~string0 := #Ultimate.alloc(261bv32);
```

Due to this behavior, checks on memory behavior are unsound, as shown by this example:

 [ctrans-bug-min-boogie-soundness-static-const-uint8.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/ctrans-bug-min-boogie-soundness-static-const-uint8.c)
```
#include <stdint.h>

typedef unsigned char uint8_t;

static const uint8_t * const pubkey[1] = {
 (const uint8_t *)"\x42",
};

int main() {
    // out of bounds access which is missed by Ultimate
    return pubkey[0][2];
}
```
As described before, Ultimate declares this string as a 4*1 + 1 byte memory area in boogie:
`call #t~string0 := #Ultimate.alloc(5bv32);`

This leads to a false negative in ignoring the out of bounds read:
```
  - PositiveResult [Line: 11]: array index is always in bounds
    For all program executions holds that array index is always in bounds at this location
[...]
  - AllSpecificationsHoldResult: All specifications hold
    4 specifications checked. All of them hold
RESULT: Ultimate proved your program to be correct!
```

Affected: including Ultimate 0.1.23-2874c22.

Toolchain and settings:
* UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml
* ~/ultimate/trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf

**Comment by danieldietsch** [comment]
@Heizmann this is also related to #307

**Comment by invd** [comment]
Ultimate 0.1.23-3c47570 is now able to spot the out of bounds access:

 ```
* Results from de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction:
  - CounterExampleResult [Line: 12]: pointer dereference may fail
    pointer dereference may fail
We found a FailurePath:
[L7]     EXPR, FCALL  "\x42"
         VAL          ["\x42"={70:0}, \old("\x42")=67, \old("\x42")=68]
[L7]     EXPR         "\x42"
[L7]     EXPR         "\x42"
[L6-L8]               static const uint8_t * const pubkey[1] = {
 (const uint8_t *)"\x42",
};
         VAL          ["\x42"={70:0}, \old("\x42")=67, \old("\x42")=68]
[L12]    EXPR         pubkey[0]
         VAL          ["\x42"={70:0}]
[L12]    FCALL        pubkey[0][2]
```

The underlying boogie code appears to be correct now regarding the buffer allocation:
```
call #t~string0 := #Ultimate.alloc(2);
```

**Comment by Heizmann** [comment]
Does this mean that your problems related to missing unicode support are solved?
I did not yet implement proper support for unicode strings and I would prefer to postpone that because it would require a further refactoring of the way how the underlying Boogie program writes strings to the heap array.

**Comment by invd** [comment]
@Heizmann: are you referring to issue #322 or this one?

**Comment by Heizmann** [comment]
Yes, sorry, I meant #316.

**Comment by invd** [comment]
The concrete issue of the buffer size miscalculation in boogie and resulting soundness problem have been found and fixed. Ultimate 0.1.23-666feb3 behaves well in this regard.

Should we close this issue, or keep it open to inspect the soundness of other string literal uses?

**Comment by danieldietsch** [comment]
Probably close to keep it concise.
