### ISSUE TITLE
Runtime slowdown accross similar programs

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#321]
_Note: feel free to add the appropriate labels._

During recent tests on supersets of the program parts referred to in other issues such as #309 and #318, it has come to my attention that the following program can only be verified in reasonable time (**~6 minutes**) if the functions `oledDrawPixel` and `oledClearPixel` are not included, while taking over **4 hours** if they are:

[partialmain_bmp_logo64_evil_Elim1Store2.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/partialmain_bmp_logo64_evil_Elim1Store2.c)
```
typedef unsigned int uint8_t;

static uint8_t _oledbuffer[1024];

typedef struct {
 uint8_t width, height;
 const uint8_t *data;
} BITMAP;

extern const BITMAP bmp_logo_mini_evil;
const uint8_t bmp_logo_mini_data[] = { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,};
const BITMAP bmp_logo_mini_evil = {16, 16, bmp_logo_mini_data};

void oledDrawPixel(int x, int y)
{
 if ((x < 0) || (y < 0) || (x >= 128) || (y >= 64)) {
  return;
 }
 _oledbuffer[((128 * 64 / 8) - 1 - (x) - ((y)/8)*128)] |= (1 << (7 - (y) % 8));
}

void oledClearPixel(int x, int y)
{
 if ((x < 0) || (y < 0) || (x >= 128) || (y >= 64)) {
  return;
 }
 _oledbuffer[((128 * 64 / 8) - 1 - (x) - ((y)/8)*128)] &= ~(1 << (7 - (y) % 8));
}

void oledDrawBitmap(int x, int y, const BITMAP *bmp)
{
 for (int i = 0; i < bmp->width; i++) {
  for (int j = 0; j < bmp->height; j++) {
   // this line is dangerous if bmp->width, bmp->height compute to an index
   // out of bounds of the actual data
   if (bmp->data[(i / 8) + j * bmp->width / 8] & (1 << (7 - i % 8))) {
    //oledDrawPixel(x + i, y + j);
   } else {
    //oledClearPixel(x + i, y + j);
   }
  }
 }
}

int main(){
  oledDrawBitmap(0, 0, &bmp_logo_mini_evil);
  return 0;
}
```
The full version of the program including the draw/clear calls is available as [partialmain_bmp_logo64_evil_Elim1Store.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/partialmain_bmp_logo64_evil_Elim1Store.c).

The program is `//#Unsafe` in both cases, as out of bounds read access will be performed on `bmp->data[]` in the conditional clause itself due to the simulated programming error in the bmp_logo_mini_evil definition. However, the `oledDrawPixel()` and `oledClearPixel()` functions are safe as they're guarded against out of bounds settings . Also note that while there are bitwise shifts and other operations present that require the `Bitvector`-type of Ultimate settings for precise calculation, they are only applied to the outputs/inputs of the array accesses and are not relevant to the array element index computation.

While this is not an urgent issue, discussion with @danieldietsch and @jhoenicke on this issue suggests that the runtime of the complete program might be improved considerably, helping in trezor analysis and many other similar cases.

For completeness, some further information:

The short run was done
* with several Ultimate versions including 0.1.23-6f35ba1
* tested settings include `AutomizerMemDerefMemtrack.xml` + `svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf`, for which output is given below
* `--traceabstraction.stop.after.first.violation.was.found false` 
* output logs were small, no sign of solver issues such as #318 
* obvious log anomalies are mainly `GenericResult: Unfinished Backtranslation` infos

```
  - CounterExampleResult [Line: 36]: pointer dereference may fail
    pointer dereference may fail
We found a FailurePath:
[...]
[L36]  FCALL        bmp->data[(i / 8) + j * bmp->width / 8]
       VAL          [\old(x)=0, \old(y)=0, bmp={1:0}, bmp={1:0}, bmp->data={-2:0}, bmp->width=16, bmp_logo_mini_data={-2:0}, bmp_logo_mini_evil={1:0}, i=0, j=4, x=0, y=0]
[...]
RESULT: Ultimate proved your program to be incorrect!
```

**Comment by invd** [comment]
Recent changes have slowed down the faster program variant (without `oledDrawPixel()` and `oledClearPixel()` calls) to a runtime of several hours. Further investigation is needed.

**Comment by invd** [comment]
Detailed analysis of the original logs from March show that during the "fast" run (without `oledDrawPixel()` and `oledClearPixel()`), no z3 invocation was made at, in contrast to the "slow" run, which includes this step that took over 3 hours:
```
[2018-03-07 11:42:24,661 INFO  L213   ckRefinementStrategy]: Switched to mode Z3_FP
No working directory specified, using /home/masterarbeit/ultimate/releaseScripts/default/UAutomizer-linux/z3
Starting monitored process 14 with z3 -smt2 -in SMTLIB2_COMPLIANT=true (exit command is (exit), workingDir is null)
Waiting until toolchain timeout for monitored process 14 with z3 -smt2 -in SMTLIB2_COMPLIANT=true
[2018-03-07 11:42:24,667 INFO  L103   rtionOrderModulation]: Keeping assertion order OUTSIDE_LOOP_FIRST2
[2018-03-07 15:21:02,526 INFO  L242   tOrderPrioritization]: Assert order OUTSIDE_LOOP_FIRST2 issued 3 check-sat command(s)
```

I will re-test this behavior with the current Ultimate/z3 combination.

**Comment by danieldietsch** [comment]
Can you post a couple of log lines before that (i.e., the reason for the switch in this iteration)?

Am 18. April 2018 15:55:03 OESZ schrieb invd <notifications@github.com>:
>Detailed analysis of the original logs from March show that during the
>"fast" run (without `oledDrawPixel()` and `oledClearPixel()`), no z3
>invocation was made at, in contrast to the "slow" run, which includes
>this step that took over 3 hours:
>```
>[2018-03-07 11:42:24,661 INFO  L213   ckRefinementStrategy]: Switched
>to mode Z3_FP
>No working directory specified, using
>/home/masterarbeit/ultimate/releaseScripts/default/UAutomizer-linux/z3
>Starting monitored process 14 with z3 -smt2 -in SMTLIB2_COMPLIANT=true
>(exit command is (exit), workingDir is null)
>Waiting until toolchain timeout for monitored process 14 with z3 -smt2
>-in SMTLIB2_COMPLIANT=true
>[2018-03-07 11:42:24,667 INFO  L103   rtionOrderModulation]: Keeping
>assertion order OUTSIDE_LOOP_FIRST2
>[2018-03-07 15:21:02,526 INFO  L242   tOrderPrioritization]: Assert
>order OUTSIDE_LOOP_FIRST2 issued 3 check-sat command(s)
>```
>
>I will re-test this behavior with the current Ultimate/z3 combination.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ultimate-pa/ultimate/issues/321#issuecomment-382376421

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by invd** [comment]
For svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf and partialmain_bmp_logo64_evil_Elim1Store2.c, runtime is about 5 minutes when only the first error location is looked at. Due to bit operations, the result is unprovable, as expected.
```
  - UnprovableResult [Line: 37]: Unable to prove that pointer dereference always succeeds
    Unable to prove that pointer dereference always succeeds
 Reason: overapproximation of bitwiseAnd at line 37.
```

When testing a similar run with the svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf profile, z3 crashed on the first run with a segfault after 2 minutes.
Dmesg output:
`[Fri Jul  6 15:52:40 2018] z3[2073]: segfault at c ip 0000000000b208fe sp 00007fffea83be50 error 4 in z3[400000+15c5000]`

Further tests will be performed in the upcoming days.

**Comment by invd** [comment]
A further run with svcomp-DerefFreeMemtrack-32bit-Automizer_Bitvector.epf and identical settings did not crash and delivered the expected result on *partialmain_bmp_logo64_evil_Elim1Store2.c* after **32** minutes.
```
- CounterExampleResult [Line: 37]: pointer dereference may fail
    pointer dereference may fail
We found a FailurePath:
```

**Comment by invd** [comment]
Running Ultimate with the -Automizer_Bitvector.epf profile on the full *partialmain_bmp_logo64_evil_Elim1Store.c* version again produced a segfault in z3, this time after about an hour:
```
[Fri Jul  6 18:38:20 2018] z3[20054]: segfault at 0 ip 0000000000d000e8 sp 00007ffdc01a5f40 error 4 in z3[400000+15c5000]
```
**[400000+15c5000]** is the same code location that triggered the last error, which suggests this is not a random issue.

@danieldietsch, @jhoenicke: is there an interest to debug this segfault further, e.g. with special versions of z3?

**Comment by invd** [comment]
On a subsequent Ultimate run with identical settings, z3 crashed again after about an hour, so this behavior appears to be reproducible.
```[Sat Jul  7 23:20:21 2018] z3[28027]: segfault at 0 ip 0000000000cfa8ae sp 00007ffcafc658d0 error 4 in z3[400000+15c5000]```
@danieldietsch: does it make sense to create a new Ultimate issue for this?

**Comment by danieldietsch** [comment]
@invd is the full version of ``partialmain_bmp_logo64_evil_Elim1Store.c`` the one stored in [examples/CToBoogieTranslation/trezor](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/partialmain_bmp_logo64_evil_Elim1Store.c) ? 

And no, a separate issue will not be necessary; I will try to reproduce this and check against the latest z3 version. If it still segfaults, we report it to the z3 team.

**Comment by danieldietsch** [comment]
This might be due to the assertion order modulation slowing down everything. This is interesting in itself but for you it might be avoidable by using ``--traceabstraction.trace.refinement.strategy CAMEL_NO_AM``.

Sadly, there is currently no equivalent for the ``Bitvector`` variant (i.e., there is no WOLF_NO_AM).

**Comment by invd** [comment]
`./Ultimate -tc ~/ultimate/releaseScripts/default/UAutomizer-linux/config/AutomizerMemDerefMemtrack.xml -s ~/ultimate/trunk/examples/settings/default/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf --traceabstraction.trace.refinement.strategy CAMEL_NO_AM` against *partialmain_bmp_logo64_evil_Elim1Store.c* 

@danieldietsch:
This refinement strategy actually makes a huge difference and Ultimate is able to reach similar conclusions (consistent to previous settings) in less than **8 minutes** instead of **18 hours** under comparable system load.

```
This is Ultimate 0.1.23-8de8874
[2018-07-09 12:11:47,594 INFO  L170        SettingsManager]: Resetting all preferences to default values...
[...]
[2018-07-09 12:19:25,792 INFO  L336   ainManager$Toolchain]: #######################  End [Toolchain 1] #######################
[...]
  - UnprovableResult [Line: 37]: Unable to prove that pointer dereference always succeeds
    Unable to prove that pointer dereference always succeeds
 Reason: overapproximation of bitwiseOr at line 20, overapproximation of bitwiseAnd at line 37.
Possible FailurePath:
[...]
```

**Comment by danieldietsch** [comment]
Very good. I will explore the assertion order modulation impact on various examples soon and then come back to this.

**Comment by invd** [comment]
@danieldietsch:
Are there any settings  you can recommend regarding further debugging of the z3 segfault, e.g. to extract inputs given to z3 inputs?

version:
```
./z3 --version
Z3 version 4.7.0 - 64 bit
```
sha256sum:
`1639b0a0afe571a774bba6f751e38d52bc445cdcf72a5abc3715168f8f1353e6  z3`

There appears to be a new official bug fix version [4.7.1](https://github.com/Z3Prover/z3/releases/tag/z3-4.7.1) from late May. I will manually copy and test the relevant z3 binary.

**Comment by invd** [comment]
Ultimate 472692297f66b14197f63de46ccd9873a7dc260c makes z3 4.7.0 reproducibly crash as well with the mentioned constellation. This happened after **5 minutes** of runtime.
```
z3[20907]: segfault at 0 ip 0000000000d000e8 sp 00007ffe123b2540 error 4 in z3[400000+15c5000]
```

I will now test z3 4.7.1  .

**Comment by invd** [comment]
4.7.1 crashes as well:
```
[2018-07-11 14:11:07,576 FATAL L265        ToolchainWalker]: An unrecoverable error occured during an interaction with an SMT solver:
de.uni_freiburg.informatik.ultimate.logic.SMTLIBException: External (z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -in -t:2000)Received EOF on stdin. No stderr output.
        at de.uni_freiburg.informatik.ultimate.smtsolver.external.Executor.parse(Executor.java:209)
```
As expected, the crash position has changed in the new binary:
```
z3[25944]: segfault at 0 ip 0000000000cb0f9f sp 00007ffe390b8b90 error 4 in z3[400000+130a000]
```

Z3 from [z3-4.7.1-x64-debian-8.10.zip](https://github.com/Z3Prover/z3/releases/download/z3-4.7.1/z3-4.7.1-x64-debian-8.10.zip) bin/z3 :
```
./z3 --version
Z3 version 4.7.1 - 64 bit

#sha256sum
53d8bdd75e3f5cf3438827be3e3bf9108126e1e94674bc54eb75a23f601b779d
```

**Comment by danieldietsch** [comment]
The z3 version in our repository is z3-4.6.0-master-2abc759d0 (2018-04-10).

You can dump the script that crashes z3 with 
````
--traceabstraction.dump.smt.script.to.file true
--traceabstraction.to.the.following.directory <arg>
      <arg> is a string representing an absolute path to a single directory on the local file system. 
````
Usually, the last ``.smt2`` file in that directory is the one that crashes z3. You can then test it by calling ``z3 -smt2 SMTLIB2_COMPLIANT=true <file>``.

**Comment by invd** [comment]
I have successfully collected 19 .smt2-files for this crash using the recommended method. Manual z3 tests are running to confirm that the last file is responsible for the crash.

**Comment by invd** [comment]
@danieldietsch:
So far, I have not been able to reproduce the crash.

When using just the recommended `z3 -smt2 SMTLIB2_COMPLIANT=true <file>`, z3 runs for a long time (75 minutes at the moment).

When using `z3 SMTLIB2_COMPLIANT=true -memory:2024 -smt2 -t:2000 <file>`, which matches the original Ultimate behavior more closely, z3 finishes within a reasonable time,  but appears to complete without error:

```
[...]
"finished trace check"
success
```
From my initial impression, the time limit `-t:2000` and not the memory limit `-memory:2024` is the main factor which causes a dramatic change in overall runtime when compared to the plain execution.

With regards to reproducing the crash : perhaps this problem depends on the stdin behavior via `-in` as well. Are there are other flags involved that Ultimate does not print?

**Comment by danieldietsch** [comment]
There are no other flags and it is rather unlikely that the segfault is due to stdin interaction. 
But it could be that the crash does not originate from trace checks but rather from other SMT queries which are performed on a separate solver instance. The log surrounding the actual crash (not only the result) usually show what happened. 

Anyways, you can also dump those other interactions, but the log file can get huge rather quick (I have seen instances as large as 300GB). 

The options for this are 
````
--rcfgbuilder.dump.smt.script.to.file true
--rcfgbuilder.to.the.following.directory <arg>
      <arg> is a string representing an absolute path to a single directory on the local file system. 
````

**Comment by invd** [comment]
@danieldietsch, @jhoenicke and myself have spent further time to debug this, but have not been able to pinpoint the exact smt2 file and argument combination that results in the segfault.

The ~4.4MB rcfgbuilder smt2-file dumped after the last comment by @danieldietsch does not crash z3.

**Comment by invd** [comment]
The capability to quickly verify [partialmain_bmp_logo64_evil_Elim1Store2.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/partialmain_bmp_logo64_evil_Elim1Store2.c) with Ultimate appears to have degraded. 
When trying it with a recent Ultimate version and the following settings, it can no longer be processed within the 6 minutes as in March 2018 - I have aborted this run after over two hours.
* AutomizerMemDerefMemtrack.xml
* svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf
* --traceabstraction.stop.after.first.violation.was.found false

This matches the experiences of long runtimes for the "full" version of the program as described in #376. I'm not sure whether the original core topic of this issue is still relevant if performance has degraded.

**Comment by invd** [comment]
The full program version cannot be verified within 48 hours, even with Automizer_Default.epf and optimized settings. 

At this point, this issue ticket has lost it's original purpose, so I think it's reasonable to close it. Feel free to reopen a new issue regarding the general slowdown for the mentioned programs/Ultimate settings.
