### ISSUE TITLE
Improve "stop after first violation" behavior

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#323]
If "stop after first violation" is false, we currently check each error location in a separate trace abstraction run. 

We can be faster if we start with checking all assertions and keep checking as long as none is violated. 
If one is violated, we could do one of the following. 
 * Remember which assertions are safe and which are unsafe, generate results for them, restart trace abstraction with the remaining assertions for which the status is not yet determined. 
 * Generate an automaton that recognizes all traces that lead to the violating location and refine with this automaton. Continue as normal. 

Both methods may have their own advantages and disadvantages, we should implement at least one of them.

**Comment by invd** [comment]
Some of the practical motivations for this feature are outlined in #324. Particularly the long runtimes over comparably simple programs with more than one likely error location have proven to be an issue for practical verification tasks with the Trezor codebase.

**Comment by Heizmann** [comment]
A good heuristic would be:
1. Store all FH automata.
2. Restart the CEGAR loop for each error location
3. Remove all dead program points
4. Reuse existing FH, but only these where each non-selfloop transition is labeled by a statement that was not removed in 3.
