### ISSUE TITLE
UnsupportedSyntaxResult: Unsupported Syntax

### ISSUE THREAD

**Issue by invd** [ultimate-pa/ultimate#325]
Ultimate has issues with this minified example taken from the trezor-mcu codebase:
[ctrans-unsupported-syntax-enum-struct.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/ctrans-unsupported-syntax-enum-struct.c)

```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator:
  - UnsupportedSyntaxResult [Line: 25]: Unsupported Syntax
    identifier is not declared (neither a variable nor a function name): RCC_CLOCK_3V3_120MHZ
RESULT: Ultimate could not prove your program: Toolchain returned no result.
Received shutdown request...
```

While this issue prevents some code fragments of the Trezor project from running, it can be worked around by manual removal and is not a real blocker there.

Further information:
* tested with Ultimate 0.1.23-6f35ba1
* settings `AutomizerMemDerefMemtrack.xml` + `svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf`

**Comment by invd** [comment]
With Ultimate 0.1.23-e3faffc, this behavior appears to have improved and no longer returns a `UnsupportedSyntaxResult` exception upon parsing.

However, the program is determined to be incorrect due to a counterexample:
```
  - CounterExampleResult [Line: 25]: array index can be out of bounds
    array index can be out of bounds
We found a FailurePath:
[L25]  FCALL  struct rcc_clock_scale clock = rcc_hse_8mhz_3v3[RCC_CLOCK_3V3_120MHZ];
       VAL    [clock={7:0}]
[L25]         rcc_hse_8mhz_3v3[RCC_CLOCK_3V3_120MHZ]
       VAL    [clock={7:0}]
```
Is this counterexample valid?

**Comment by jhoenicke** [comment]
This bug was fixed, but new problem above is due to a new bug, see #333.

**Comment by invd** [comment]
As documentation: `Is this counterexample valid?` -> No, due to #333, Ultimate did not correctly handle the values assigned to the enum members, which led to an incorrect counterexample.
This is now fixed.

Ultimate 0.1.23-f020fd9:
```
 * Results from de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction:
  - PositiveResult [Line: 23]: all allocated memory was freed
    For all program executions holds that all allocated memory was freed at this location
  - PositiveResult [Line: 25]: array index is always in bounds
    For all program executions holds that array index is always in bounds at this location
  - AllSpecificationsHoldResult: All specifications hold
    2 specifications checked. All of them hold
[...]
RESULT: Ultimate proved your program to be correct!
```
