### ISSUE TITLE
default arrays/array constants in Boogie

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#329]
Setting:
I would like to support something like the following in Boogie
```
  var a : [int] int;
  a := defaultArray_0; 
```
where "defaultArray_0" is a constant array that has 0 at every index.
 (probably "defaultArray_0" is a bad name, I'm open to suggestions)

Applications:
 - easier testing for #327, once it is implemented
 - groundwork for #259

My current state of understanding:
 I do not see how this can be solved by our current Boogie-SMT bridge.

my attempts:
1. ```function { :builtin "@0" } ~defaultArray~0() returns (out : [int] int);``` :
 (EDIT: it should be "```(as @0 (Array Int Int))```" instead of "```@0```", still does not work though)
 Problems: 
   - does not seem to type in SMT (but types in Boogie)
   - specific to SMTInterpol even if it would work
2. ```function defaultArray_0 (index : int) returns (out : int) { out == 0 }``` 
  Problem: does not type in Boogie if I assign the function to an array, right?

**Comment by Heizmann** [comment]
What exactly is the SMT-LIB syntax for a constant array?

**Comment by alexandernutz** [comment]
after discussion with @jhoenicke  : 
 - there is no standard SMT-LIB syntax for this
 - some solvers have specific solutions, I would have to look into each one

 - workaround in current SMT-LIB:
```
(declare-const defaultArray_0 (Array Int Int))
(assert (forall ((i Int)) (= (select defaultArrray_0 i) 0))
```
obvious problem: introduces a quantifier

 - Something like
```
(define-fun defaultArrray_0 ...)
```
does not work, because functions cannot be assigned/do not have array type.

 - Probably z3 has a solution for this, but I would have to do more research, perhaps some kind of lambda expressions..
 - SMTInterpol does not have a solution at the moment (the syntax ```(as @0 (Array Int Int))``` is only allowed during model evalutation).

**Comment by Heizmann** [comment]
(These are not good news...)
I presume that the solution with the quantifier is too expensive.
For us, it might be sufficient if we have a solution that works with Z3 and if we could convince the SMTInterpol developers to use the same syntax.
However, I really dislike solutions that are not standard compliant.

**Comment by alexandernutz** [comment]
According to [z3 documentation](https://rise4fun.com/z3/tutorial/guide) constant arrays are expressed like this:
```((as const (Array Int Int)) 0)```

For model creation/evalutation there is also a conversion from functions to arrays, but like the SMTInterpol construct mentioned above this does not seem to work inside input constraints:
```(_ as-array f)``` converts a previously defined function to an array

I suppose the first solution could be right for us.

**Comment by alexandernutz** [comment]
after discussion with @jhoenicke : 
```((as const (Array Int Int)) 0)```
should be relatively easy to build into Ultimate, and seems to be a solution that SMTInterpol might support in the future, too.

To support it, we would only have to add an internal function ```const``` of the right (polymorphic) type.

**Comment by Heizmann** [comment]
I do not completely understand the term.
`` ((as const (Array Int Int)) 0)``
What I understand is
* the `as` says that here the return sort of the function symbol ``const`` is `(Array Int Int)`
* this function is applied to `0`

I am wondering about the following.
* Does one have to declare the function symbol ``const``?
* Does ``const`` have a special meaning for Z3? ( and hence it does not have to be declared)
* Does your logic package already support `as`?

**Comment by Heizmann** [comment]
Ok, I think I understand.
I think the keyword `const` is too generic is will be difficult to get this into the SMT-LIB standard. But if Z3 has it then let's use it too.
If @jhoenicke thinks this is a good idea then let's add this to our logic package.

Is it allowed to define a shorthand for the function where the sort is already instantiated?
`(define-fun const-Array-Int-Int (x Int) (Array Int Int) ((as const (Array Int Int)) x)`
This might make it less difficult to extend our translation from Boogie to SMT. But I do not yet have a precise idea in mind.

**Comment by alexandernutz** [comment]
Adding this just for a more complete picture:
 Today I stumbled over this in [smtlib 2.6]http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf   (page 31):
```(as (const-array 0.0) (Array Int Real ))```
which seems to be an alternative notation for what we want.
However this only occurs in a code example and I found no other place in the standard that would explain this notation.

I could not get it running with either cvc4 or z3.. -- so I'm in favour of sticking with the notation discussed above.
Next I will look into z3-style notation more closely, and try to figure out what needs to be done to add it to our logic package.

**Comment by alexandernutz** [comment]
Concerning the shorthand mentioned above:
```(define-fun const-Array-Int-Int ((x Int)) (Array Int Int) ((as const (Array Int Int)) x))```
 -- this should work. It works in z3 right now, and our implementation should support it, too.

To summarize:
 - we introduce a new predefined function "const" into our array theory
 - the sort of const is "(X) (Array Y X)".

**Comment by alexandernutz** [comment]
I implemented the discussed changes, but there is a technical problem:
whenever z3 receives a ```(set-logic ..)``` command, it deactivates the ```const``` function for some reason (logics I tried: ALL, AUFNIRA, QF_AUFLIRA).
Do we have a way of starting z3 without a logic?
 I tried this by giving ```null``` as ```logicForExternalSolver``` argument for ```SolverBuilder.buildAndInitializeSolver```, but then we do not create a Theory and crash as soon as it is needed..  ( with an ```SMTLIBException("No logic set!")``` )

I guess one approach would be to write to the z3 programmers about this. But if there is a fast workaround, I would consider that first..

**Comment by Heizmann** [comment]
>  Do we have a way of starting z3 without a logic?

No.

**Comment by alexandernutz** [comment]
Works for my purposes at the moment so I am closing the issue. Note that the flag in SolverBuilder is required to switch on the definition of the ```const-Array-Int-Int``` convenience function, and that no Solver besides recent versions of Z3 recognizes the syntax.
