### ISSUE TITLE
ModifiableGlobalsTable vs IcfgTransformation

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#334]
I am wondering about a couple of things regarding "modifiable globals" and icfg transformations.
 - Q1: Say, a Transformula is transformed during an IcfgTransformation and an update to a (possibly fresh) global variable is introduced. Where is (or should be) the ModifiedGlobalsTable updated accordingly?
 - Q2: How/Where is it ensured that the ModifiedGlobals table stays consistent with the call graph? ("transitive modified globals")
   (Do we store a call graph in a non-Boogie Icfg?)
 - Q3: Should we introduce a sanity check in an assertion, like we have for Boogie programs for this? (I'm in favour of this.)

Note that the PredicateTransformer becomes unsound if the ModifiableGlobalsTable is not consistent with the Transformulas of an Icfg.

**Comment by Heizmann** [comment]
- A1: Should not be modified. Construct a new one.
- A2: Not at all.
- A3: Good idea.

**Comment by danieldietsch** [comment]
The question for me is: how soon do you need it? 
For Q1: I think the workaround is easy, just build your own (you already added something in f0cda2c afaik). 
For Q2: How severe would performance suffer if you just added the global as modified global to all procedures? This is easy. I can implement the real thing soonish, but this week is rather limited for me. 
For Q3: Yes, sounds good, but is connected to Q2.

**Comment by alexandernutz** [comment]
I need it to get a sound heap separator, and I would like to find out if that is the last soundness issue soonish.
On the other hand I just saw that SAS deadline got pushed back one week, and there are other things I should do for it, too. Let's discuss it in person..
