### ISSUE TITLE
PrenexNormalForm, NNF does not work with negated quantifiers

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#354]
See example in ``XnfTransformerTest``:
````
[DEBUG]: ORG: (exists ((k Int)) (= (not (= 0 k)) (= 1 k)))
[DEBUG]: NNF:(exists ((v_nnf_1 Int)) (let ((.cse0 (= 1 v_nnf_1)) (.cse1 (= 0 v_nnf_1))) (or (and (not .cse0) .cse1) (and .cse0 (not .cse1)))))
[DEBUG]: PNF:(exists ((v_nnf_1 Int)) (let ((.cse0 (= 1 v_nnf_1)) (.cse1 (= 0 v_nnf_1))) (or (and (not .cse0) .cse1) (and .cse0 (not .cse1)))))
[DEBUG]: ORG: (not (exists ((k Int)) (= (not (= 0 k)) (= 1 k))))
[DEBUG]: NNF:(not (exists ((k Int)) (= (not (= 0 k)) (= 1 k))))
--> Dies because PNF says that NNF is not NNF
````

**Comment by schillic** [comment]
Makes sense, because negations are not allowed in [prenex normal form](https://en.wikipedia.org/wiki/Prenex_normal_form) :wink:

**Comment by danieldietsch** [comment]
Yes, obviously. Perhaps the title is misleading. The NNF transformation is the issue, but I do not want to fix it (pushing negation inwards and flipping quantifiers) without consulting with Matthias first.

**Comment by Heizmann** [comment]
Please use the NnfTransformer with the argument KEEP instead of PULL.
The idea of PULL is to do NnfTransformation and PnfTransformation in one shot. But I don't know if it is a good idea.

**Comment by danieldietsch** [comment]
KEEP exhibits the same behavior.

**Comment by danieldietsch** [comment]
5b3ff88e488df2f60c2403790cf911fb6e92800a fixed the issue with KEEP, thanks.
