### ISSUE TITLE
Passing settings for Block Encoding does not always work

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#355]
Can sometimes be reproduced by 

``trunk/examples/programs/toy/InvariantChecking/ArrayInitialization01.bpl``
``trunk/examples/toolchains/RefereeBpl.xml``
and the default settings

You get the AssertionError 
*Either subgraph not acyclic or there is a bug* 
from AcyclicSubgraphMeger.

**Comment by danieldietsch** [comment]
There are multiple issues with your example  
 * The file is a Boogie file, the toolchain is for C programs 
 * If I use ``AutomizerBpl.xml``,  ``AcyclicSubgraphMerger`` is never instantiated. 
 * I tried various other toolchains, none of them instantiated ``AcyclicSubgraphMerger``

**Comment by Heizmann** [comment]
Posted the wrong toolchain.
Sorry.
Fixed above (`trunk/examples/toolchains/RefereeBpl.xml`)
