### ISSUE TITLE
Replace string debug identifier in ``IcfgLocation`` by dedicated types to reduce memory load 

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#369]
**Problem**  
For certain situations, the debug identifiers generated by various transformations contain very large strings that consume an unnecessary amount of memory. 
One occurrence is the transformation of requirements to Boogie. There, we do not have line numbers of our input. This triggers an edge case where most of the debug identifiers are of the form ``L1(')^n``, with ``n`` between 1 and ~110000. 

**Solution**  
Instead of using a string to represent this identifier (which has a memory requirement of ``(no. of chars * 2 + 38)`` rounded up to the next multiple of 8) we can use a dedicated type. 

We need to distinguish at least 4 cases 
1. Symbols for internal locations: ``L`` followed by a number followed by some amount of `` ` ``   
1. Symbols for procedure entries 
1. Symbols for procedure exits 
1. Symbols for error locations : procedure name followed by ``Err`` followed by a number followed by the type of error location (e.g., ``AssertViolation``)

Replacing each of these cases with a dedicated object should reduce memory usage considerably. 
For example, case 1 can be replaced with an object having only two ``int`` fields, i.e., memory usage should then be 16 byte (8 for the object itself, 4 for each of the ints). 

We need to ensure that
- all currently available information is still available 
- each location needs its own debug identifier 
- we want to see when a location was created (i.e., ``L23''`` is the third location created for line 23)

**Question** Is there anything I am forgetting?

**Comment by Heizmann** [comment]
I do not want to distract from the topic that current implementation of the DebugIdentifier is not optimal. But if you would not have a large Boogie Input in which the whole program is in one single line you would not have this problem.
There might be other related problems because when I implemented this I neither optimized performance nor usability for single line programs.

**Comment by danieldietsch** [comment]
This is true.
