### ISSUE TITLE
Assertion error during CFG2NestedWordAutomaton

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#371]
AssertionError with the following Boogie file: 
[test.bpl.txt](https://github.com/ultimate-pa/ultimate/files/2214492/test.bpl.txt)

````
java.lang.AssertionError: Cannot add #21#return;, missing callerNode __U_MULTI_f_storage_ultimate_releaseScripts_default_DeltaDebugger_linux_test_c__mutex_unlockENTRY
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.CFG2NestedWordAutomaton.constructAutomaton(CFG2NestedWordAutomaton.java:194)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.CFG2NestedWordAutomaton.constructAutomatonWithSPredicates(CFG2NestedWordAutomaton.java:88)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.BasicCegarLoop.getInitialAbstraction(BasicCegarLoop.java:299)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterateInternal(AbstractCegarLoop.java:393)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.AbstractCegarLoop.iterate(AbstractCegarLoop.java:367)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.iterate(TraceAbstractionStarter.java:309)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.runCegarLoops(TraceAbstractionStarter.java:151)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionStarter.<init>(TraceAbstractionStarter.java:119)
        at de.uni_freiburg.informatik.ultimate.plugins.generator.traceabstraction.TraceAbstractionObserver.finish(TraceAbstractionObserver.java:123)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runObserver(PluginConnector.java:168)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.runTool(PluginConnector.java:151)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.PluginConnector.run(PluginConnector.java:128)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.executePluginConnector(ToolchainWalker.java:232)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.processPlugin(ToolchainWalker.java:226)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walkUnprotected(ToolchainWalker.java:142)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainWalker.walk(ToolchainWalker.java:104)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.ToolchainManager$Toolchain.processToolchain(ToolchainManager.java:316)
        at de.uni_freiburg.informatik.ultimate.core.coreplugin.toolchain.DefaultToolchainJob.run(DefaultToolchainJob.java:145)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
````
Call is 
``-tc toolchains/AutomizerBpl.xml ``
``-i test.bpl ``
``-s settings/default/automizer/svcomp-Reach-64bit-Automizer_Default.epf``

**Comment by danieldietsch** [comment]
Hm, interesting. I assumed that such a transition can never be taken in an Icfg. Is this not the case?

**Comment by Heizmann** [comment]
What is "such a transition"?

We have not yet defined precisely what a valid ICFG is. Hence, I cannot say if something like the `IcfgLocationIterator` is suiteable for finding set of reachable locations.

**Comment by danieldietsch** [comment]
Q1: 
> I could now ignore all return edges where the predecessor location of the corresponding call is never returned by your IcfgLocationIterator.

This sounds like a good solution if my answer Q3 is ok for you and if the ``IcfgLocationIterator`` actually adheres to my answer for Q3.

Q2: 
> What is "such a transition"?
>> The ICFG has a return transition such that the predecessor location of the corresponding call is
__U_MULTI_f_storage_ultimate_releaseScripts_default_DeltaDebugger_linux_test_c__mutex_unlockENTRY
However, your IcfgLocationIterator never returns this location because it is not reachable from the initial location.

For the future I will try to avoid all kinds of words like it, such, they, them, etc. 

Q3:
> We have not yet defined precisely what a valid ICFG is. Hence, I cannot say if something like the IcfgLocationIterator is suiteable for finding set of reachable locations.

This is somewhat suprising to me. I thought we had a shared understanding of what an ICFG is. I have a rather precise definition based on [1] in my thesis. Note that this has nothing to do with validity, only with reachability of locations in an Icfg. 

As far as reachability is concerned I would say: 
"A location ``loc`` of an Icfg is reachable if ``loc`` is an initial location or if there exists a path ``pi`` from an initial location to ``loc`` such that all return transitions ``e_return = ({loc_i,loc_call}, loc_j)`` on the path ``pi`` are preceeded by a (possibly empty) sequence of internal transitions and the call transition ``e_call = ({loc_call},loc_k)`` that corresponds to ``e_return``.

[1] Thomas W. Reps, Susan Horwitz, and Shmuel Sagiv. Precise Interprocedural Dataflow Analysis via Graph Reachability. In POPL 1995, pages 49–61, 1995.

**Comment by Heizmann** [comment]
* So according to your definition every return transition has a *corresponding* call transition.
Pro: makes the reachability analysis (and maybe other things?) easier.
Con: we will not be able to translate all intermediate results of the trace abstraction back to an ICFG. Affected are e.g., *path programs with unwindings*.
* Your definition says nothing about a stack, so a sequence `call foo` `call bar` `return foo` `return bar` would be finde.
* Are explicit summary edges required? I think they are required in the paper.

**Comment by schillic** [comment]
To simplify the definition, I guess @danieldietsch wants to say this:
An ICFG location `loc` is reachable if the *corresponding nested word automaton*¹ with set of accepting states {`loc`} has a non-empty language.

¹I think this definition is clear.

**Comment by danieldietsch** [comment]
> So according to your definition every return transition has a corresponding call transition.

Yes. Is this not the case? I do not know what path programs with unwindings are. 

> Your definition says nothing about a stack, so a sequence call foo call bar return foo return bar would be fine.

No. First of all, I do not talk about sequences, only about reachability of locations. If you want to say: which locations are reachable in an ICFG where ``l0`` is an initial location and the transition relation of the ICFG is ``E= { ({l0},(l1)),  ({l1},l2), ({l2,l0},l3), ({l3,l1},l4) }``, then only ``l0, l1`` and ``l2`` are reachable. 
This is because the sequence ``call foo call bar return foo return bar`` has a call (``call bar``) that is not corresponding to a return (``return foo``) before a return instead of only internal transitions up to the call that is corresponding to the return. 

> Are explicit summary edges required? I think they are required in the paper.

No summary edges are not required.

> To simplify the definition, I guess @danieldietsch wants to say this:
An ICFG location loc is reachable if the corresponding nested word automaton¹ with set of accepting states {loc} has a non-empty language.

No. I want to avoid the relation to nested word automata. 

> ¹I think this definition is clear.

Yes, I agree. For people who know what nested word automata are.

**Comment by schillic** [comment]
>>    Your definition says nothing about a stack, so a sequence call foo call bar return foo return bar would be fine.
>
> No. First of all, I do not talk about sequences, only about reachability of locations. If you want to say: which locations are reachable in an ICFG where l0 is an initial location and the transition relation of the ICFG is E= { ({l0},(l1)), ({l1},l2), ({l2,l0},l3), ({l3,l1},l4) }, then only l0, l1 and l2 are reachable.
This is because the sequence call foo call bar return foo return bar has a call (call bar) that is not corresponding to a return (return foo) before a return instead of only internal transitions up to the call that is corresponding to the return.

According to your definition, in the sequence `call foo, call bar, return bar, return foo` (note that I changed the order) the location after `return foo` is not reachable. This is not intuitive for me.

**Comment by Heizmann** [comment]
> path programs with unwindings 
I wrote that in italics because we do not yet have a term for that.
You know "path programs" which are a projection of path to ICFG.
Let's assume we have a path that unwinded some loop 5 times. Maybe we want to have something similar than a path program, where this loop is also unwinded 5 times.

**Comment by danieldietsch** [comment]
> According to your definition, in the sequence call foo, call bar, return bar, return foo (note that I changed the order) the location after return foo is not reachable. This is not intuitive for me.

Right, that looks bad. Perhaps the nested word definition is nicer. Can you write it in full here?

**Comment by danieldietsch** [comment]
> path programs with unwindings

But how would the resulting path program have a return transition without corresponding call?

**Comment by Heizmann** [comment]
There are several calls that could match (only one for each concrete run but there might be many possible runs).

**Comment by schillic** [comment]
> Perhaps the nested word definition is nicer. Can you write it in full here?

I do not think that there is a concise way of writing it down. This is the version I know:

A well-matched word (WMW) is defined recursively:
- A (possibly empty) sequence of internal statements is an WMW.
- If `w1`, `w2`, and `w3` are WMW, then `w1.call f.w2.return f.w3` is an WMW.

A matched-return word (MRW) is a sequence
`w1.call f1.w2.callf2...call fk.wk+1`
where the `wi` are WMW.

With this definition, I would define:
A location `loc` is reachable if there exists a path from an initial location to `loc` such that the statements along the path form an MRW.

**Comment by danieldietsch** [comment]
@schillic what is ``f`` in your definition?

**Comment by schillic** [comment]
Just some function names. I updated the text.

**Comment by danieldietsch** [comment]
Ok, that looks good. And it seems that it does not really need much from nested word automata, right?

**Comment by danieldietsch** [comment]
Btw I had in the meantime a look at the ``IcfgLocationIterator`` -- the comment reads: 
````
/**
 * Iterates all locations of an {@link IIcfg} that are reachable in its graph view, i.e., all locations reachable by
 * following outgoing edges from initial nodes. "Graph view" means in particular: we may iterate over locations only
 * reachable via return transitions that had no matching call transition.
...
 */
````
So, the iterator does not care at all for nesting.

**Comment by Heizmann** [comment]
> Perhaps there is a third behaviour that Matthias would like to have for the iterator (e.g. just looking at the various maps of the Icfg and iterating over these). We can also do that.

No, I think we cannot. All ICFG plugins would then depend on the AutomataLibrary and a re-implementation of the reachability analysis would be too complicated.

**Comment by Heizmann** [comment]
Regarding the bug:
I proposed a solution. @danieldietsch said I should implement that solution in case IcfgLocationIterator adheres so something that was stated in **Q3** above. The further discussion showed that IcfgLocationIterator does not adhere to what was stated in **Q3** 

So let me propose again.

> I could now ignore all return edges where the predecessor location of the corresponding call is never returned by your IcfgLocationIterator.

**Comment by Heizmann** [comment]
Regarding the problem of the missing semantics:
I cannot see how we could define the semantics without nested word automata, visibly pushdown automata, or pushdown automata.
Just using nested words is not sufficient. It does not tell you which return has to match which call.
