### ISSUE TITLE
Add images to the documentation in our wiki

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#379]
In the wiki we can easily include images if the images are available somewhere in the internet.
But where should we host these images? The wiki does not provide the possibility to upload images.

Solutions:
* Host images somewhere else in the internet.
* Upload images to some folder in the ultimate repository
* ...

**Comment by schillic** [comment]
As far as I know, the wiki is just another git repository. You can check it out locally and add a folder with the images.

**Comment by Heizmann** [comment]
And which folder should we pick? Any opinions?

**Comment by schillic** [comment]
`git clone https://github.com/ultimate-pa/ultimate.wiki.git`
There is already a folder `img`. But you should probably start adding subfolders.

**Comment by danieldietsch** [comment]
@schillic said it all :)
