### ISSUE TITLE
AssertionError: not an integer constant: null:

### ISSUE THREAD

**Issue by gschievelbein** [ultimate-pa/ultimate#382]
As of the log from 28.09.2018, there are 60 occurrences of the exception:
 de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: AssertionError: not an integer constant: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.TypeHandler.constructEnumValue(TypeHandler.java:814):

**Comment by gschievelbein** [comment]
> For any other enumerator whose definition does not have an initializer, the associated value is the value of the previous enumerator plus one.

https://en.cppreference.com/w/cpp/language/enum

```
enum
  {
    A, //A=0
    B = A + 50, //B=0+50=50
    C //C=51
  };
```

For the code above, the exception occurs when trying to attribute the value of C.

**Comment by gschievelbein** [comment]
Ok. So, what's happening is that the value of B is of type BinaryExpression, and the function to calculate the value of C expects and Integer constant, and adds 1.

Is the type of B being a BinaryExpression the expected behaviour? In this case, the value of C should also be a BinaryExpression(left = previous BinExpr, right = 1), correct?

**Comment by alexandernutz** [comment]
I would expect that if we allow a binaryExpression for B, we also allow one for C. However, it is also sometimes useful to have the calculated value of enum constants --> SymbolTableValue has the field mConstantValue for this purpose.
I'm not sure about the details, but I would say
 - assign ((A + 50) + 1) to C
 - check that the corresponding symbolTableValue stores the IntegerLiteral 51 in its mConstantValue

**Comment by gschievelbein** [comment]
Instead of attributing a new BinaryExpression value to the enum value, we are computing the value of the previous enum, so, so for the minimal example, the IntegerLiteral 51 would be attributed to C.

The solution for bitvector is still missing.

**Comment by danieldietsch** [comment]
But should be similar, right?

**Comment by gschievelbein** [comment]
Yes, I did it similarly now for bitvector settings.

**Comment by danieldietsch** [comment]
Nice. So we can close this issue?

**Comment by gschievelbein** [comment]
Yes
