### ISSUE TITLE
AssertionError: null:

### ISSUE THREAD

**Issue by gschievelbein** [ultimate-pa/ultimate#385]
As of the log from 28.09.2018. 

373  ExceptionOrErrorR...      de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: AssertionError: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.result.LRValueFactory.constructHeapLValue(LRValueFactory.java:11):

109  ExceptionOrErrorR...      de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator: AssertionError: null: de.uni_freiburg.informatik.ultimate.cdt.translation.implementation.base.chandler.MemoryModel_Unbounded.getDataHeapArray(MemoryModel_Unbounded.java:95):

**Comment by gschievelbein** [comment]
Ok. Those errors also appear in the previous log from 23-09, and are present in the dev branch, as of 00a862152b4a22febbefb6c1a359a272ba3d6d94

**Comment by danieldietsch** [comment]
Yes, we should definitely fix them regardless of the branch. I just wanted to ensure that you are aware of the source of the log. 

The idea is that ``wip/dd/ctrans`` will be merged into dev as soon as it performs better than dev on the C translation. I think I only need to fix the error class `` AssertionError: cannot convert to CFunction: `` to accomplish that.
