### ISSUE TITLE
Support variadic functions

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#390]
We want to support variadic functions as described in https://en.cppreference.com/w/c/variadic . 

Until recently this was not an issue because most examples that contain variadic functions do not use them. 

Since we retired ``determineNecessaryDeclarations``, we fail on these examples without this support.

**Comment by danieldietsch** [comment]
Relevant resources: 
 * The Wikipedia entry regarding pointers to va_list: https://en.wikipedia.org/wiki/Stdarg.h 
 * The definition of ``va_list`` in System V ABI: 
https://stackoverflow.com/questions/4958384/what-is-the-format-of-the-x86-64-va-list-structure
````
// Figure 3.34
typedef struct {
   unsigned int gp_offset;
   unsigned int fp_offset;
   void *overflow_arg_area;
   void *reg_save_area;
} va_list[1];
````
 * https://en.cppreference.com/w/c/variadic
 * https://en.cppreference.com/w/c/language/variadic
 * https://en.cppreference.com/w/c/variadic/va_list
 * https://en.cppreference.com/w/c/variadic/va_start
 * https://en.cppreference.com/w/c/variadic/va_arg
 * https://en.cppreference.com/w/c/variadic/va_end
 * https://en.cppreference.com/w/c/language/conversion#Default_argument_promotions
 
The basic plan is as follows.
 * Declare ``va_list`` as separate type per variadic function and call-site. 
 * The type for a function and a call-site is a global struct ``fun-variadic-call-i`` consisting of 
   * ``n`` fields, 
   * an integer ``n`` that represents the amount of fields that were assigned at the call-site, and 
   * an integer ``idx`` that represents which field is the "active" field (ranging from 0 to n-1),
   * an integer ``max`` that represents the maximal number of arguments obtainable from this struct in this iteration. 
 * The type of each field has to be inferred from the corresponding call site (sharing is possible, but an enhancement).
 * The declaration order of the fields corresponds to the order in which the arguments are passed.
 * The translated variadic function has to be duplicated and adapted for each translated ``va_list`` type, calls have to match. 
 * Before a call to a variadic function, 
   * the arguments are promoted with default argument promotions, 
   * the global ``fun-variadic-call-i`` is initialized with the promoted arguments in their order, 
   * ``n`` is set to the amount of parameters, 
   * and ``idx`` and ``max`` are set to -1 
 * ``va_start(va_list ap, parmN)`` is translated as 
   * check that ``parmN`` is smaller than ``n``
   * modifying the matching ``fun-variadic-call-i``  s.t. ``idx == 0`` and ``max == parmN``
 * ``va_end(va_list ap)`` is translated as
   * check that the matching ``fun-variadic-call-i`` idx != -1 and max != -1 
   * set idx == -1 and max == -1 
 * ``T va_arg( va_list ap, T )`` is translated as 
   * check that the matching ``fun-variadic-call-i`` idx != -1 and max != -1 
   * check that the type of the field at position ``idx`` is compatible with type T (see also https://en.cppreference.com/w/c/variadic/va_arg) 
   * check that idx+1 is smaller than max 
   * increment idx by 1 
   * evaluate to the value of the field at idx-1 
 
Implementation
 * Introduce ``StandardTypeHandler`` similar to ``StandardFunctionHandler``  
 * TBD

**Comment by Heizmann** [comment]
Makes sense.
* if cannot be done off-heap
* we are unable to check if the type is compatible in va_arg
* parmN is something in the source file not an expression that can provide an int value
* we need to introduce a new kind of undefined behavior for this
* We should not use a struct and copies of the function but an array and one instance of the function. The optimization with the structs is nice but too complex for the start.

If we have a C function `foo(T1 arg1, T2 arg2, ...)` the corresponding Boogie procedure should look as follows

```
procedure foo(arg1 : T1, arg2 :T2, #vaLength : int, #vaList : [int]$Pointer$) returns () {
  var #vaIdx : int;
  var #vaMax : int;
  vaIdx := -1;
  vaMax := -1;
...
```

A call of the form `foo(a,b,c,d,e)` where c is a char, d is a float and should be translated as follows
auxPointerC := #Ultimate.alloc(8);
auxPointerD := #Ultimate.alloc(8);
auxPointerE := #Ultimate.alloc(8);
auxVaList_Call27[0] = auxPointerC;
auxVaList_Call27[1] = auxPointerD;
auxVaList_Call27[2] = auxPointerE;
#Ultimate.writeInt(c, auxPointerC, 1);
#Ultimate.writeFloat(c, auxPointerD, 4);
#Ultimate.writePointer(c, auxPointerD, 8);
call foo(a,b, 3, auxPointerC, auxPointerD, auxPointerE)
havoc auxVaList, auxPointerC, auxPointerD, auxPointerE
