### ISSUE TITLE
Bitvector translation is very slow for large expressions

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#396]
The problem occurs at location
`C: ret = cafe_smbus_write_data(cam, (int )addr, (int )command, (int )data->byte) [5512]`

We construct a large expression of the following form.
`StructAccessExpression[IdentifierExpression[~data,<LOCAL,cafe_smbus_xfer>],offset] + 1 + 1 + ... + 1`

The integer translation can construct this expression within seconds.
The bitvector translation does not terminate (within minutes) and spends time in ExpressionFactory#constructFunctionApplication.

Input: trunk/examples/svcomp/ldv-linux-3.14-races/linux-3.14--drivers--media--platform--marvell-ccic--cafe_ccic.ko_false-unreach-call.cil.i
Toolchain: some with CTranslation
Settings: default

**Comment by Heizmann** [comment]
Some additional note.
I am usually against simplifying non-constant expressions (e.g. `(((x+1) + 1) + 1)`) at this level. Because this makes it more difficult to match the result to the original code (and at the moment useless if we also check for overflows).
I am however not strictly against simplification for expressions that do not occur in the code and are created by us is order to compute an address.
We could e.g. have a (relatively simple) optimization that checks for a sum (A+B) if one the operands are also sums and moves constants to the front. E.g. `( (3+y) + (5+x) )` would become `(8 + (y + x))`.

**Comment by danieldietsch** [comment]
Good to hear. I think I can fix the performance issue by not trying to simplify the arguments (and thus all sub expressions). I can also add this optimization.

**Comment by danieldietsch** [comment]
You are right, I worded that badly. I mean I do not descend into the argument expressions anymore. If they are literals, we simplify, but if they are not, we do not look if they themselves have somewhere deep down some expression we can simplify. Should be safe as long as we always create function applications with the factory.
