### ISSUE TITLE
Regression failure for congruence closure

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#397]
@alexandernutz I think this is your corner; can you take a look? 

https://monteverdi.informatik.uni-freiburg.de/ci/job/Ultimate%20Nightly/de.uni_freiburg.informatik.ultimate$de.uni_freiburg.informatik.ultimate.lib.util.test/1910/testReport/de.uni_freiburg.informatik.ultimate.util/CongruenceClosureTest/testContainsConstraints03/

**Comment by schuessf** [comment]
Seems to be fixed
