### ISSUE TITLE
Feature Request: Possibility to create small data structure mock-ups for unit testing

### ISSUE THREAD

**Issue by greitsch** [ultimate-pa/ultimate#4]
For unit testing of some low-level implementations, it would be desirable to be able to create mock-ups of small data structures, such as a BoogieVar, without having to parse a whole Boogie program with a full Ultimate tool chain.

Currently, the creation process of a BoogieVar needs some SMT TermVariables, and ApplicationTerms which are not be available if one doesn't want to parse a whole Boogie program. Therefore, perform unit testing only on methods (without the whole Ultimate back-end) that require BoogieVars is impossible. For example, if a function that should be tested computes some values for which only the existence of BoogieVars is necessary, but the semantics of said BoogieVars is irrelevant, it would be nice to be able to create instances of BoogieVars which serve that purpose.

Additionally, it would also be nice to be able to create mock-ups of Boogie CodeBlocks from strings. E.g. by using  "var x : int; x := 5", the CodeBlock data structure for those two statements is created (through parsing) to be able to test e.g. implementations that handle assignment operations.

**Comment by danieldietsch** [comment]
Is this still relevant? We now have mockups for SMT formulas and for Boogievars, but not for CodeBlocks.

**Comment by danieldietsch** [comment]
Not specific enough.
