### ISSUE TITLE
AssertionError: invalid Hoare triple in Craig

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#403]
`java -ea -Xmx8000000000 -jar /storage/repos/ultimate/releaseScripts/default/UAutomizer-linux/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -data @noDefault -ultimatedata /storage/repos/ultimate/releaseScripts/default/UAutomizer-linux/data -tc ../../../trunk/examples/toolchains/AutomizerC.xml -s ../../../trunk/examples/settings/default/automizer/svcomp-Reach-32bit-Automizer_Default.epf -i ../../../trunk/examples/svcomp/ldv-regression/ex3_forlist_true-termination.c_true-unreach-call.i
`

**Comment by danieldietsch** [comment]
This example now triggers ``java.lang.AssertionError: select-over-store with same index should have been removed``

**Comment by Heizmann** [comment]
Problem approached in https://github.com/ultimate-pa/ultimate/commit/5cbab9aaaa708e48dbc447abbdf6370cb0a1e165
Not reproducible with original example.
Reproducible with following example.
Reproducible with `trunk/examples/svcomp/array-memsafety/cstrcspn-alloca_true-valid-memsafety_true-termination.i`
	`trunk/examples/settings/svcomp2017/automizer/svcomp-DerefFreeMemtrack-32bit-Automizer_Default.epf `
`trunk/examples/toolchains/AutomizerC.xml`
Solution: Transform Interpolants from solver into Ultimate Normal Form.

**Comment by danieldietsch** [comment]
The initial example does not trigger the error anymore using Ultimate 0.2.1-dev-be40b96 (be40b96).
