### ISSUE TITLE
Pointercast with Integer translation leads to unsoundness

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#410]
The following example for property
     valid-deref valid-free valid-memtrack
yields the result ``true`` with our integer translation although ``false`` is correct.

````
int areNatural(int *numbers){
    int i = 0;
    while(i < 10) {
        if(numbers[i] <= 0){
            return 0;
        }
        i++;
    }
    return 1;
}

int main(void) {
    char numbers[] = {0,1,2,3,4,5,6,7,8,9};
    // numbers is array of chars, but should be integers
    int result = areNatural((int*) numbers);
    return 0;
}
````

Issue  
Cast from char pointer to int pointer, then wrong read due to memory model (0 instead of concatenaton of 4 chars). 

Possible solutions  
 * Use 1Byte resolution and bitvector translation for memsafety. 
 * let integer translation crash if there is a pointer cast

**Comment by maul-esel** [comment]
@danieldietsch Fixed by fc023d8 and dea106e ?

**Comment by danieldietsch** [comment]
@maul-esel Did you check the example?

**Comment by maul-esel** [comment]
With Integer translation (`svcomp-DerefFreeMemtrack-64bit-Automizer_Default.epf`):
> Unsupported Syntax: Found a cast between two array/pointer types where the value type is smaller than the cast-to type while using memory model HoenickeLindenmann_Original (while Not using bitvector translation)

With Bitvector translation (`svcomp-DerefFreeMemtrack-64bit-Automizer_Bitvector.epf`):
> CounterExampleResult [Line: 4]: pointer dereference may fail

The above example is part of the sv-benchmarks and was the original motivation for the mentioned commits.
