### ISSUE TITLE
mathsat does not support fp.rem and roundNearestTiesToAway

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#412]
mathsat does not support ``fp.rem`` and ``roundNearestTiesToAway`` from the FP theory. 

We can include these messages in our checks for solver crashes -- and we should try and ask them to support it.

**Comment by gschievelbein** [comment]
In a somewhat related problem, in SMT there is not negative NAN. How should we deal with that in the implementation of standard functions that require the sign value, such as signbit and copysign?

**Comment by schuessf** [comment]
This problem still occured in our [regression tests](https://jenkins.sopranium.de/job/Ultimate/job/Ultimate%20Nightly/job/dev/1119/testReport/de.uni_freiburg.informatik.ultimate.regressiontest.generic/RegressionTestSuite/I_programs_FloatingPoint_regression_c_all_ctrans_float_round_c_S_programs_FloatingPoint_regression_c_AutomizerC_Reach_32bit_WOLF_Float_epf_T_programs_FloatingPoint_regression_c_AutomizerC_xml/) (and also in the SV-COMP), therefore I added this message to the ignored exception messages as proposed.
