### ISSUE TITLE
You must have same procedures except when you have threads or when this is a call or a return

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#420]
`trunk/examples/programs/quantifier/regression/c/SimpleArrayTest-Bounds02_OnHeap.c`, 
default settings 
`trunk/examples/toolchains/AutomizerC.xml`

Error message
> You must have same procedures except when you have threads or when this is a call or a return

However, preceding and succeeding procedure coincide.

**Comment by maul-esel** [comment]
The failing assertion compares procedure names for reference equality. In this case, the two occurrences of `"main"` are not reference-equal.

**Comment by maul-esel** [comment]
Should be fixed by d4cc249
