### ISSUE TITLE
iCfg to CHC translation

### ISSUE THREAD

**Issue by alexandernutz** [ultimate-pa/ultimate#421]

**Comment by alexandernutz** [comment]
Implement a plugin that translates from an icfg/rcfg to a set of constrained Horn clauses (CHCs) such that the  CHC-set is satisfiable iff the icfg is correct/safe.

**Comment by danieldietsch** [comment]
@alexandernutz can this issue be closed?

**Comment by schuessf** [comment]
There is a plugin [Library-CHC](https://github.com/ultimate-pa/ultimate/tree/dev/trunk/source/Library-CHC) with this functionality.
