### ISSUE TITLE
Add results to Ultimate Eliminator

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#432]
The webinterface for our quantifier elimination, Ultimate Eliminator, is missing results. 
https://monteverdi.informatik.uni-freiburg.de/tomcat/Website/?ui=int&tool=eliminator

This will require a flag or object for ``UltimateEliminator`` that specifies whether results should be created for -- at least -- each ``(check-sat)`` of the input ``.smt2`` file.

**Comment by maul-esel** [comment]
The current web interface shows results at least for `check-sat` and `simplify` commands.
