### ISSUE TITLE
RCFG builder logs annoying error message

### ISSUE THREAD

**Issue by schaetzc** [ultimate-pa/ultimate#434]
The RCFG builder writes an error to the log saying

`[<date> ERROR L160 MonitoredProcess]: Could not determine absolute path of external process, hoping that OS will resolve z3`

Note that this is only an error *message* and not an actual error as the RCFG builder works for me. Is there any way to disable this log message?

I have `z3` installed in `/usr/bin/z3` and my `$PATH` contains `…:/usr/bin:…`.

**Comment by schaetzc** [comment]
Found the problem. It is a linux-specific bug in Ultimate.
Ultimate searches `$PATH` for files named `z3` such that

    file.isFile() && file.canExecute() && funLooksLikeExectuable.test(file)

However, `funLooksLikeExectuable` is broken on linux. It checks the magic number of the file in such a way that no file can ever *look like an executable*:

	final FileInputStream input = new FileInputStream(f);
	input.read(firstBytes);
	input.close();
	if (firstBytes[0] == 0x7f && firstBytes[1] == 0x45 && firstBytes[1] == 0x4c && firstBytes[1] == 0x46) {
		return true;
	}
	return false;

Note that we check `firstBytes[1] == 0x45 == 0x4c == 0x46`.

I fixed the problem in 01a7f49fed91d1ebad6f79117f2917df7c476f8e.

**Comment by schaetzc** [comment]
We were lucky that the magic numbers used only bytes < 128. Otherwise the comparison would have failed in a less obvious way. Because bytes are signed `(byte) 0xFF != 0xFF`.
In 47adba0bcc1620dd583490251eafdb49ec8aa4dc I fixed this problem from ever occurring by explicitly requiring bytes.

**Comment by schaetzc** [comment]
@danieldietsch The old code read two times as many bytes as it actually compared. On Linux 8 bytes were read even though the magic number was only 4 bytes long. On Windows 4 bytes were read even though the magic number was only 2 bytes long. The new code reads the as few bytes as necessary which works fine for me on Linux. If there is some reason to read more than that feel free to change  https://github.com/ultimate-pa/ultimate/blob/febf1e04c05fc858b7dd54ef66e6c78e1e1df432/trunk/source/Library-UltimateUtil/src/de/uni_freiburg/informatik/ultimate/util/CoreUtil.java#L173
to

     final byte[] firstBytes = new byte[2 * magicNumber.length];

If you do so, please let me know why this is important. I'm eager to learn more.

**Comment by danieldietsch** [comment]
No, this was an additional bug -- seems like you fixed them all and made much nicer code, thank you for that!
