### ISSUE TITLE
PredicateTransformer does not eliminate AuxVar

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#441]
PredicateTransformer.strongestPostconditionCall contains Auxvars of call transition in resulting term. 

To observe the behavior:
  * Set break point at https://github.com/ultimate-pa/ultimate/blob/3036a875e7fda7b2aab1b90aa0f53c74f5d6a4d6/trunk/source/Library-SymbolicInterpretation/src/de/uni_freiburg/informatik/ultimate/lib/symbolicinterpretation/SymbolicTools.java#L125
  * Example [examples/BoogiePL/sifa/iprogramvar-bug/iprogramvar-bug.bpl](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/BoogiePL/sifa/iprogramvar-bug/iprogramvar-bug.bpl)
  * Toolchain ``Sifa.xml``

**Comment by Heizmann** [comment]
Is a bug. I know how to fix it, I am planning to do so within the next 24 hours.

**Comment by Heizmann** [comment]
I am unable to produce a good test for the real problem. @danieldietsch could you fix #442 first?

**Comment by danieldietsch** [comment]
I can take a look.
