### ISSUE TITLE
Add testgenerator assertions for final phases that only have an edge.

### ISSUE THREAD

**Issue by Langenfeld** [ultimate-pa/ultimate#457]
For some cases of requirements, the last phase is not part of a pea phase but is enforced by an edge. In this case the test generator has no assertions to generate tests.

Assertions can be added by checking if one of those edges is taken (done)
but as a subsequent phase is needed to get a test that is missing its last step the violation of the test generator assertion has to be delayed by one phase (todo)

**Comment by danieldietsch** [comment]
I.e., we will generate more tests if this is finished
