### ISSUE TITLE
Fix AI bug "recursive-wrong-prestate.bpl"

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#46]
`examples/programs/abstractInterpretation/regression/recursive-wrong-prestate.bpl`

> // Wrong (not inductive) transition and/or state added by AI
> // The second disjunct of the hierachical pre state is probably the reason. 
> // 
> // PreState:			(and (= foo_bla 0) (= foo_res 0))
> // HierachicalPreState 	(or (<= 1 foo_bla) (<= (+ foo_bla 1) 0))
> // Trans: 				return;
> // Post:				(and (= foo_res 0) (<= 1 foo_bla))

**Comment by greitsch** [comment]
Do we already know whether this is an AI bug or a bug in the construction of the interpolant automaton?
