### ISSUE TITLE
LTL property parsing

### ISSUE THREAD

**Issue by thpani** [ultimate-pa/ultimate#477]
The following LTL property spec results in a parsing exception in the LTL Automizer [web interface](https://monteverdi.informatik.uni-freiburg.de/tomcat/Website/?ui=int&tool=ltl_automizer), but works fine with the [binary version](https://monteverdi.informatik.uni-freiburg.de/tomcat/Website/?ui=tool&tool=ltl_automizer) `LTLAutomizer_Linux64_r13621.zip`.

```c
//@ ltl invariant positive: (([]<>AP(env == 0) <==> []<>AP(env == 1)) && ([]<>AP(trans == 1) <==> []<>AP(trans == 2))) ==> []<>AP(crit == 1);

int crit = 0;
int env = 0;
int trans = 0;

int main() {
  crit++;
  env++;
  trans++;
}
```

The exception is

    de.uni_freiburg.informatik.ultimate.ltl2aut: Exception: Can't recover from previous error(s): 
    com.github.jhoenicke.javacup.runtime.LRParser.report_fatal_error(LRParser.java:286)

**Comment by Heizmann** [comment]
Thanks for reporting the problem.
I tried to fix the web interface but unfortunately, I broke it completely.

**Comment by maul-esel** [comment]
The web interface has since been fixed; the given example works now (correctness is proven after some minutes).
