### ISSUE TITLE
UniversalityPatternDelayed

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/ultimate#489]
- [x]  Implement this pattern.
- [ ]  Discuss how to solve the s/r-conflict caused by AFTER between ...
- IT IS ALWAYS THE CASE THAT expression:p HOLDS
- IT IS ALWAYS THE CASE THAT expression:p HOLDS AFTER AT MOST duration:d
- [ ]  Change pattern from "... holds at most c1 later" to "...holds after at most c1".

**Comment by danieldietsch** [comment]
@hauff Check if it now (after bf3f3ee) works as expected:

**Comment by danieldietsch** [comment]
@hauff Could you please confirm?

**Comment by henkele** [comment]
Works as expected.
