### ISSUE TITLE
Check modified counter traces

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/ultimate#492]
I think the modified counter traces are correct.
To be safe, please double check ...

- [x] 5a250b6dd720590f3b5fae56d7d901fa904c82dd
- [x] 507ae921eeb7b312c5cf0e8374946673cace5b08, 3bcbae76fa9087960cc5f636386aa89b4d8f615d

**Comment by danieldietsch** [comment]
Looks good to me. 

But lets use pull requests for reviews instead of issues :)
