### ISSUE TITLE
UReqCheck External (z3 -smt2 -in SMTLIB2_COMPLIANT=true) Connection to SMT solver broken

### ISSUE THREAD

**Issue by IridescentL** [ultimate-pa/ultimate#497]
I downloaded the latest ureqcheck release file and ran the script run_complete_analysis.sh with a ".req" file to analyze it. When the program finished running, I opened the log file, found an error "External (z3 -smt2 -in SMTLIB2_COMPLIANT=true) Connection to SMT solver broken". How to solve this problem? I ran the script on CENTOS 7 and the network is good.

**Comment by danieldietsch** [comment]
Can you post the log output?

**Comment by IridescentL** [comment]
![image](https://user-images.githubusercontent.com/24289271/92371489-3e0c3b00-f12e-11ea-8bc7-f8ebf13f024e.png)
![image](https://user-images.githubusercontent.com/24289271/92371673-7ad83200-f12e-11ea-8bc5-3efa7cf5538d.png)

**Comment by danieldietsch** [comment]
Oh, this means that z3 crashed trying to solve some initial query. Can you share the ``.req`` file so that I can have a look?

**Comment by IridescentL** [comment]
![image](https://user-images.githubusercontent.com/24289271/92391575-86882080-f14f-11ea-9ce2-ee00f96d031d.png)

**Comment by danieldietsch** [comment]
Perhaps not as screenshot but as an attachment?

**Comment by IridescentL** [comment]
sry...
[example_input.req.zip](https://github.com/ultimate-pa/ultimate/files/5183369/example_input.req.zip)

**Comment by danieldietsch** [comment]
Can you try our latest nightly build from https://monteverdi.informatik.uni-freiburg.de/ultimate-nightly/ and use ``./run_complete_analysis.py -ar example_input.req`` ?

**Comment by IridescentL** [comment]
![image](https://user-images.githubusercontent.com/24289271/92397055-acfe8980-f158-11ea-9a05-ef1645bfab7d.png)
wow! I think it works! The log file generated contains corrent results, that is, this ".req" file itself is erroneous.
Next I will try analyzing other .req files. Hope everything will be fine.
MANY THANKS for your support!

**Comment by danieldietsch** [comment]
You are welcome! If you run into any more trouble, do not hesitate to open a ticket.
