### ISSUE TITLE
trunk/source/Website/WebContent/json missing

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#5]
For building the webinterface, we the folder 
``trunk/source/Website/WebContent/json``
is needed. Problem: Git does not support empty folders.
How should we fix this?
1. Add an auxiliary file in the folder.
2. Let convertHTMLtoJSON.jar create the folder.
3. ???

**Comment by danieldietsch** [comment]
I would say we create the folder with convertHTMLtoJSON.jar

I will fix this tomorrow.
