### ISSUE TITLE
Wrong specification in ReqAnalyzer regression test vacuity_test42

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/ultimate#506]
- Jenkins: [history](https://monteverdi.informatik.uni-freiburg.de/ci/job/Ultimate%20Nightly/2594/de.uni_freiburg.informatik.ultimate$de.uni_freiburg.informatik.ultimate.regressiontest/testReport/de.uni_freiburg.informatik.ultimate.regressiontest.generic/ReqCheckerRegressionTestSuite/I_Requirements_regression_vacuity_vacuity_test42_req_S_Requirements_regression_ReqCheck_SmtInterpol_epf_T_Requirements_regression_ReqCheck_xml/history/)
- Hanfor: [constraint](https://ultimate-pa.github.io/hanfor/references/patterns.html#universalitypattern-globally), [req1](https://ultimate-pa.github.io/hanfor/references/patterns.html#bndrecurrencepattern-globally)

### Result
- Expected: rt-inconsistent:; vacuous:req1; inconsistent:;
- Actual: rt-inconsistent:; vacuous:; inconsistent:;

### Test (.req file)
```
CONST time_every is 10.0

Constraint_assumption: Globally it is always the case that "!var3" holds
req1: Globally It is always the case that "var3" holds at least every "time_every" time units
```

### Comments
Actual should be correct.

#### constraint
`Countertraces: (true;⌈!Q⌉;true)`

![image](https://user-images.githubusercontent.com/13038993/92761546-15847b00-f392-11ea-833e-e2d63225150e.png)

#### req1
`Countertraces: (true;⌈!Q⌉ ∧ ℓ > 5;true)`

![image](https://user-images.githubusercontent.com/13038993/92761801-4ebceb00-f392-11ea-91f6-a6d2b8f512ca.png)

**Comment by hauff** [comment]
Actual matches implementation.
But, does the behavior match the definition of vacuity?

**Comment by danieldietsch** [comment]
Is actually rt-inconsistent ; see latest version
