### ISSUE TITLE
C - Ternary Operator introduces (unreachable) error

### ISSUE THREAD

**Issue by blizzard4591** [ultimate-pa/ultimate#510]
Dear Ultimate team,

my student and I discovered a case where the introduction of an additional ternary operator introduces a bug.

two_ternary.c:_
```
extern void __VERIFIER_error();
char var1 = 0;
char var2 = 0;
void step(void) {
	if (var2) {
		var1 = (1);
	}
}

int property() {
	return (1) ? ((var2) ? (var1 == (1)) : (1)) : (1);
}
int main(void) {
	while (1) {
		step();
		if (!property()) {
			__VERIFIER_error();
		}
	}
	return 0;
}
```

This slightly modified version has the same property (semantic-wise), but without the useless outer ternary operator.
one_ternary.c:
```
extern void __VERIFIER_error();
char var1 = 0;
char var2 = 0;
void step(void) {
	if (var2) {
		var1 = (1);
	}
}

int property() {
	return (var2) ? (var1 == (1)) : (1);
}
int main(void) {
	while (1) {
		step();
		if (!property()) {
			__VERIFIER_error();
		}
	}
	return 0;
}
```

Ultimate (0.1.25) reports a reachable error on the two_ternary.c case:
```
CounterExampleResult [Line: 23]: a call of __VERIFIER_error() is reachable
    a call of __VERIFIER_error() is reachable
We found a FailurePath:
[L3]               char var1 = 0;
[L4]               char var2 = 0;
       VAL         [var1=0, var2=0]
[L20]  COND TRUE   1
       VAL         [var1=0, var2=0]
[L8]   COND FALSE  !(\read(var2))
       VAL         [var1=0, var2=0]
[L15]              return (1) ? ((var2) ? (var1 == (1)) : (1)) : (1);
[L22]  COND TRUE   !property()
[L23]              __VERIFIER_error()
       VAL         [var1=0, var2=0]
```

and an unreachable error without the second ternary:
```
  - PositiveResult [Line: 23]: call of __VERIFIER_error() unreachable
    For all program executions holds that call of __VERIFIER_error() unreachable at this location
  - AllSpecificationsHoldResult: All specifications hold
    1 specifications checked. All of them hold
  - InvariantResult [Line: 18]: Loop Invariant
    Derived loop invariant: 0
  - InvariantResult [Line: 13]: Loop Invariant
    Derived loop invariant: 1 <= \result && var2 == 0
  - InvariantResult [Line: 20]: Loop Invariant
    Derived loop invariant: var2 == 0
```

**Comment by danieldietsch** [comment]
Thank you for the report, Ill look into it.

**Comment by maul-esel** [comment]
Problem was in the translation from C to Boogie. The version with 2 ternaries was translated as
```bpl
implementation property() returns (#res : int){
    var #t~ite0 : int;

    #res := #t~ite0;
    havoc #t~ite0;
    return;
}
```
After commit ccf5fd5 it is now correctly translated as
```bpl
implementation property() returns (#res : int){
    var #t~ite0 : int;

    if (0 != ~var2~0) {
        #t~ite0 := (if 1 == ~var1~0 then 1 else 0);
    } else {
        #t~ite0 := 1;
    }
    #res := #t~ite0;
    havoc #t~ite0;
    return;
}
```
(exactly the same as the one-ternary version).

Since this should fix the bug, I'm closing the issue. Feel free to re-open if I am wrong :)

**Comment by Heizmann** [comment]
But why is the outer ternary operator translated to an if-then-else statement and the inner ternary operator translated to an if-then-else operator? @maul-esel

**Comment by maul-esel** [comment]
They are (would be) both translated to if-then-else statements (presumably because expression evaluation in C might have side-effects). However, the outer ternary is optimized away, because its condition is the constant `1`. Only the "then"-Branch (i.e., the inner ternary) remains.

The if-then-else operator you see is simply the conversion of a boolean expression to an integer.

**Comment by Heizmann** [comment]
Thanks for the explanation. I just realized that my question was kind of "stupid". We usually cannot translate large C expression directly into Boogie expression because of side-effects. The ternary operator is a perfect example for this.
