### ISSUE TITLE
[Question] How to represent responses to signal edges (ReqCheck)

### ISSUE THREAD

**Issue by alopez-developair** [ultimate-pa/ultimate#526]
We would like to know how to formalize the behavior of reacting to a signal edge, such as a response to entering or exiting a state. With our current knowledge, we would have tried with something like:

```
Globally, it is always the case that if "A" holds, then "B" will hold after at most "5" time units.
```

The diagram represents a trace for A and two possible traces of B. By my original intention, I'd like `B_edge` to be a valid trace. However, this formalization would require B to be active again further down the line, such that for example something like what is represented as `B_req` would be an actual valid trace.

![wavedrom](https://user-images.githubusercontent.com/57357066/97844804-f1874b00-1ceb-11eb-855f-3032014d9219.png)

The question would be: how may we formalize my original intention correctly so that `b_edge` becomes a valid trace? Basically, any trace where B gets set on those first 5 time units would have to be valid, regardless of how long A remains active.

**Comment by mmartinezDevelopair** [comment]
We have more doubts about the interpretation that the reqchecker makes. In those examples we have two boolean variables "Estado" and "Motor". "Estado" restricts "Motor" in some way and the diagrams represent two possible cases. We want to know which of them is the correct one.

1. "Globally, it is always the case that if "Estado==1" holds, then "!Motor" holds for at least "5" time units"

![Example 1](https://user-images.githubusercontent.com/70137072/98921615-cbbf2a80-24d1-11eb-92b3-5748cb84595e.jpg)

2. "Globally, it is always the case that if "Estado==1" holds for at least "5" time units, then "!Motor" holds afterwards for at least "2" time units"

![Example 2](https://user-images.githubusercontent.com/70137072/98921767-f3ae8e00-24d1-11eb-9ac7-8e68d9df7c95.jpg)

In case that the valid traces are the second ones, how can we formalize the first trace in each example?

**Comment by Langenfeld** [comment]
@mmartinezDevelopair in both cases it is the green version for the same reason. In each interval that is fulfilling ``Estado == 1``, there holds that threre is an inerval ``Motor`` for the next 5 resp. 2 time units.

To formulate what you are looking for, we need to implement the  After version of a UniversalDuration Pattern, for the second an after version of the BndDelayedResponsePatternUT.

**Comment by alopez-developair** [comment]
For the first case at the top, I feel like we are trying to express something that would have the following DC counterformula:

```c
true;⌈!A⌉;⌈(!B && A)⌉;⌈!B⌉ ∧ ℓ > 5;true
```

The closest thing I can come up with is:
```
After "!A", it is always the case that if "A" holds, then "B" will hold after at most "5" time units.
```

But as per [the hanfor docs](https://ultimate-pa.github.io/hanfor/references/patterns.html#bndresponsepatternut-after), this would translate to:

```c
true;⌈!A⌉;true;⌈(!B && A)⌉;⌈!B⌉ ∧ ℓ > 5;true
```

Which doesn't seem to be what we want as by my interpretation this only requires `!A` to have held somewhere in the past, not immediately before changing to `!A`.

> To formulate what you are looking for, we need to implement the After version of a UniversalDuration Pattern, for the second an after version of the BndDelayedResponsePatternUT.

Do you mean BndInvariancePattern instead of UniversalDuration?

In any case, the above would apply to all three examples, where the After scope wouldn't seem to help formulating exactly what we mean.
