### ISSUE TITLE
Requirements pattern for "Once a Flank has been seen, (x holds for c | x holds after at most c for d)

### ISSUE THREAD

**Issue by Langenfeld** [ultimate-pa/ultimate#529]
We need Patterns for formulating requirements like (see #526)

1. ``Globally, once  "Estado==1" holds, then "!Motor" holds for at least "5" time units``
2. ``Globally, once  "Estado==1" holds, then "!Motor" holds after at most "2" time units for at least "5" time units.``

with formlua like

```
true;⌈!A⌉;⌈A⌉;⌈B⌉ ∧ ℓ < 5;⌈!B⌉;true
```

**Comment by henkele** [comment]
The following should work..

1. BndEdgeResponsePattern:
``Globally, it is always the case that once "Q" becomes satisfied, "R" holds for at least "t" time units.``
   ```
    true;⌈!Q⌉;⌈Q⌉;⌈R⌉ ∧ ℓ < t;⌈!R⌉;true                    (R  does not hold for at least t)
    true;⌈!Q⌉;⌈(Q && !R)⌉; true                            (R directly holds at the rising edge of Q)
   ```

2. BndEdgeResponsePatternDelayed:
``Globally, it is always the case that once "Q" becomes satisfied,  "R" holds after at most "t1" time units for at least "t2" time units.``
   ```
    true;⌈!Q⌉;⌈(Q && !R)⌉;⌈!R⌉ ∧ ℓ > t1;true                (R does not hold after at most t1)
    true;⌈!Q⌉;⌈Q⌉; true ∧ ℓ < t1;⌈R⌉ ∧ ℓ < t2;⌈!R⌉;true     (R holds after at most t1, but not for at least t2)
   ```

**Comment by Langenfeld** [comment]
Ok, we did miss the pattern from the first comment in #526, and have to add that @henkele (my bad).

**Comment by henkele** [comment]
@Langenfeld This one ?

``Globally, it is always the case that if "A" holds, then "B" will hold after at most "5" time units.``

**Comment by Langenfeld** [comment]
Yes. But I think that this should be less of a problem after we have found the formulas for the other two.

**Comment by henkele** [comment]
3. EdgeResponsePatternDelayed:
``Globally, it is always the case that once "Q" becomes satisfied, "R" holds after at most "t" time units.``
   ```
    true;⌈!Q⌉;⌈(Q && !R)⌉;⌈!R⌉ ∧ ℓ > t;true
   ```

**Comment by alopez-developair** [comment]
Just wanted to chime in to say that, also, in #526 we had 

```
Globally, it is always the case that if "Estado==1" holds for at least "5" time units, then "!Motor" holds afterwards for at least "2" time units
```

rather than

```
Globally, once "Estado==1" holds, then "!Motor" holds after at most "2" time units for at least "5" time units.
```

(I mean BndResponsePatternTT rather than BndDelayedResponsePatternUT)

**Comment by Langenfeld** [comment]
To clarify this, so we should ''Globally, it is always the case that if "Estado==1" holds for at least "5" time units, then "!Motor" holds afterwards for at least "2" time units'' @alopez-developair?

**Comment by alopez-developair** [comment]
Yes. Something like
```
Globally, it is always the case that once "Q" becomes satisfied and holds for "t" time units, then "R" holds afterwards for at least "u" time units
```

Perhaps modeled with:

```c
true;⌈!Q⌉;⌈Q⌉ ∧ ℓ = t;⌈R⌉ ∧ ℓ < u;⌈!R⌉;true
```

We did realize that in this case in the precondition, it is no longer "at least" but rather "exactly". Could this be a problem implementation-wise?

**Comment by henkele** [comment]
Yes, we can not implement exact time bounds because these formulae are then no longer in the counterexample fragment of duration calculus.

**Comment by alopez-developair** [comment]
Right, I seemed to recall reading that exact time bounds were not possible. We'll have to reconsider this one.

**Comment by mmartinezDevelopair** [comment]
We have done some tests with the new patterns and we wanted to give you some feedback about them:

### **- BndEdgeResponsePattern**

**- Example 1**

Input R IS bool
Output Q IS bool
R1: Globally, it is always the case that if "R" holds, then "!Q" holds after at most "1" time units for at least "3" time units.
R2: Globally, it is always the case that once "R" becomes satisfied, "Q" holds for at least "3" time units.
Q1: Globally, it is always the case that "R" holds at least every "5" time units 
Q2: Globally, it is always the case that once "R" becomes satisfied, it holds for less than "5" time units 

Result: RT-Inconsistency between R1 and R2. 

We found a FailurePath: 
INITIAL     Q=* R=*
[0;1/2]     Q=* R=false
[1/2;1]     Q=true R=true

We found a FailurePath: 
INITIAL     Q=* R=*
[0;1/4]     Q=true R=true
[1/4;1/2]   Q=false R=true
[1/2;5/4]   Q=false R=false

It is the first time that we see two counterexamples for the same error. ¿Does it make sense?

**- Example 2**

Input R IS bool
Output Q IS bool
req1: Globally, it is always the case that if "R" holds, then "!Q" holds after at most "5" time units
req2_Edge: Globally, it is always the case that once "R" becomes satisfied, "Q" holds for at least "3" time units.
Q1: Globally, it is always the case that once "R" becomes satisfied, it holds for less than "5" time units 
Q2: Globally, it is always the case that once "R" becomes satisfied, it holds for at least "3" time units 
Q3: Globally, it is always the case that "R" holds at least every "10" time units.

Result: RT-Inconsistency between req1 and req2_Edge. 

We found a FailurePath: 
INITIAL     Q=* R=*
[0;1/2]     Q=* R=false
[1/2;1]     Q=true R=true
[1;4]       Q=true R=false

Our interpretation: In t=0,5 there is a rising edge of R, so req2_Edge forces Q to be activated from t=0,5 to t=3,5. At the same time, whenever R=True, it happens that Q=True, so req1 is fulfilled. We do not understand the error and the counterexample.

### **- BndEdgeResponsePatternDelayed**

Input in1 IS bool
Output Q IS bool
Internal State is bool

R_StateTransition: Globally, it is always the case that if "State && in1" holds, then "!State" holds after at most "10" time units.
R_Invariance: Globally, it is always the case that if "State" holds, then "!Q" holds for at least "4" time units.
R_Edge: Globally, it is always the case that once "!State " becomes satisfied, "Q" holds after at most "1" time units for at least "5" time units.

Result: RT-Inconsistency between R_Invariance and R_Edge and Vacuity R_Edge

We found a FailurePath: 
INITIAL     |'State|=true Q=* in1=* State=true
[0;1/2]     |'State|=true Q=false in1=false State=true
[1/2;3/2]   |'State|=true Q=false in1=true State=false

Our interpretation: We understand the error and the counterexample
    - t=0-0,5: State==true --> R_invariance forces !Q from t=0 to t=4,5
    - T=0,5: Falling edge of State --> R_Edge forces Q from t=1,5 to t=4,5

However, we do not understand the Vacuity in R_Edge

**Comment by henkele** [comment]
- Example 1
  >  It is the first time that we see two counterexamples for the same error. ¿Does it make sense?

  Both R1 and R2 consist of two ct-formulas. So basically we have requirements R1.1, R1.2, R2.1 and R2.2 involved in the rt-inconsistency check (using the order as given in the Hanfor documentation).
The first failure path shows an rt-inconsistency between R1.1 and R2.2, the second refers to the rt-inconsistency between R1.2 and R2.2. So if there is more than one ct-formula involved in a requirement, you may see more than on failure path.

- Example 2
With the newest version of ultimate I get a different failure path for this example
  ```
  Requirements req2_Edge, req1 are rt-inconsistent
  We found a FailurePath: 
  INITIAL     Q=* R=*
  [0;1/2]     Q=true R=true
  [1/2;2]     Q=true R=false
  [2;7/2]     Q=true R=true
  ```
  At t=2.5:
  "Q" should be set to 0 to not violate req1, however to not violate req2_Edge it must be 1 for at least two more time units.

- Example 3
R_Edge triggers its action on a falling edge of "State", so R_Invariance will always be triggered before "State" switches from 1 to 0. The last phase of R_Edge can thus never be reached as R_Invariance always forces "!Q" to hold for at least 4 time units
