### ISSUE TITLE
Ambiguous meaning of bounded phase representation in ce-traces

### ISSUE THREAD

**Issue by henkele** [ultimate-pa/ultimate#535]
The phase ⌈P⌉ is defined by: ``⌈P⌉ ⟺ ∫ P = ℓ ∧ ℓ > 0``

The length of a bounded phase ``⌈P⌉ ∧ ℓ ~ t``  with ``~∊{<,>,≤,≥}`` can thus not be 0 by definition .

Currently we have two possible implementations of bounded phases.

1.  ```phase(P, ~, t)``` which exactly matches ``⌈P⌉ ∧ ℓ ~ t``

2. ```phaseE(P, ~, t)``` which additionally allows the phase to be empty, i.e. of length ``ℓ = 0``.
So this is basically ``(⌈P⌉ ∧ ℓ ~ t)  ∨ ⌈⌉``
When generating countertrace formula representations of the implemented countertraces, we do not  distinguish  between the different implementations of a bounded phase. We should use an unambiguous representation.

**Comment by henkele** [comment]
I would suggest something like ⌈P⌉<sub>ε</sub> ∧ ℓ ~ t to express that the phase could also be an empty phase.
@danieldietsch @Langenfeld Any thoughts or suggestions?

**Comment by henkele** [comment]
I would prefer an subscript 0 along with the boundtype, like ⌈Q⌉∧ ℓ ≤₀  5, any objections @danieldietsch @Langenfeld ?

**Comment by danieldietsch** [comment]
Do you propose to change the implementation or the representation in output and docs? 

For the latter, yes, subscripts is nice. 
For the former: What is the new name?

**Comment by henkele** [comment]
Only the String representation, especially for the documentation, as right now one needs to have a look at the implementation to be a 100 percent sure

**Comment by henkele** [comment]
fixed by 6c98aa044b4282b66b01e4e74b9589422c0abdad
