### ISSUE TITLE
Jordan acceleration unsound on loop-invariants/linear-inequality-inv-a.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#551]
Version c3a52b3

Jordan Acceleration with IcfgTransformation yields wrong result on `loop-invariants/linear-inequality-inv-a.c`, and IcfgTransformation transforms at least one loop.

The call was 
`/usr/bin/java -Xmx8000000000 -Xss4m -jar ./plugins/org.eclipse.equinox.launcher_1.5.800.v20200727-1323.jar -data @noDefault -ultimatedata ./data -tc ../../../trunk/examples/toolchains/AutomizerCTransformed.xml -s ../../../trunk/examples/settings/automizer/LoopAccelerationJordanC.epf -i ../../../trunk/examples/svcomp/loop-invariants/linear-inequality-inv-a.c
`

The log:
https://struebli.informatik.uni-freiburg.de/logs/student-acceleration/20210416-091202-student-acceleration-259539aefe-M/student-acceleration.2021-04-15_22-53-33.logfiles/Automizer%20IcfgTranformation%20Jordan.linear-inequality-inv-a.yml.log

**Comment by Heizmann** [comment]
f420631da00b6d8dd6b3227ed5d9acc3978fc3cd fixed a soundness bug that lead to an incorrect loop acceleration on this example. Currently I cannot reproduce incorrect results here.
