### ISSUE TITLE
Timeouts are not respected in some scenarios

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#567]
In different situations, Ultimate does not respect timeouts.
* When a global or per-assertion timeout is set, trace check solvers should also be started with an appropriate timeout
* Refinement engine does not check timeouts during strategy execution
* Multi-assert timeouts seem to be buggy
* Some test cases do not respect timeouts (in particular ` Input:Requirements/regression/vacuity/vacuity_test82.req Settings:Requirements/regression/ReqCheck-SmtInterpol.epf Toolchain:Requirements/regression/ReqCheck.xml`)

**Comment by Heizmann** [comment]
I added support for timeouts to the PolyPacSimplification  https://github.com/ultimate-pa/ultimate/commit/8aad492c62750135f07d8e711c3dd8ada32d89da

**Comment by Heizmann** [comment]
The formula of https://github.com/ultimate-pa/ultimate/commit/eb3cadcabc632d055530954edd331d399b5f1469 has a very complex Boolean structure but rather few atoms. Maybe (maybe!) our SimplifyDda-based simplifications are not very helpful here and BDD-based simplifications would perform better.

**Comment by danieldietsch** [comment]
It seems like we catched all these issues.
