### ISSUE TITLE
UReqCheck usage problem

### ISSUE THREAD

**Issue by IridescentL** [ultimate-pa/ultimate#574]
Is there any way to only check the rt-consistency and get the corresponding time consumption with UReqCheck? That is to say, skip all other analysis procedure and keep only the rt-consistency check, and get its running time. Need your help! Thanks!

**Comment by danieldietsch** [comment]
Hi @IridescentL, 
I am unsure what you are trying to do. Do you want to disable vacuity and consistency checks? 

If you just want to compare speeds, you might want to start without the wrapper script.
