### ISSUE TITLE
maven repository down

### ISSUE THREAD

**Issue by linusboyle** [ultimate-pa/ultimate#575]
Trying to build ultimate here. Two of the repositories are not accessible, namely `https://monteverdi.informatik.uni-freiburg.de/nexus/content/repositories/cdt-10.0/` and `https://monteverdi.informatik.uni-freiburg.de/nexus/content/repositories/eclipse-4.17`. Requesting any file such as `content.xml` etc. gives a 404.

**Comment by danieldietsch** [comment]
There seems to be an issue upstream, I am investigating.

**Comment by danieldietsch** [comment]
Upstream is working again, our cache has caught up as well.
