### ISSUE TITLE
Fix examples\CToBoogieTranslation\MultidimensionalArrays.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#58]

**Comment by alexandernutz** [comment]
This example does several evil things:
 - declare an array of size 0
 - use an empty initializer

C11 6.7.6.2.1 states:
 If the expression [inside the square brackets, ed.] is a constant expression, it shall have a value greater than zero.

So I believe we should rather fix any such benchmarks than the C translation.

Also the grammar in 6.7.9 does not allow empty initializer lists.

**Comment by danieldietsch** [comment]
I am unsure as to were those examples are from. If they are from SV-COMP, then we have to take it up with them.
