### ISSUE TITLE
ReqChecker -java error

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/ultimate#602]
With hanfor documentation:
![image](https://user-images.githubusercontent.com/99885690/194050187-bd45a14e-9dbd-4c89-a602-3ee3799a1b33.png)

I use the command "python run_complete_analysis.py -ar  xxx.req" in UReqcheck-linux, the ReqChecker didn't work:

![image](https://user-images.githubusercontent.com/99885690/194050865-1cb5cb46-120c-456a-82d4-3a9aee2974f2.png)

![image](https://user-images.githubusercontent.com/99885690/194050740-794c8ce9-efdd-4d78-bb15-79865567ce83.png)

**Comment by hauff** [comment]
Is discussed in [Hanfor issue 231](https://github.com/ultimate-pa/hanfor/issues/231).
