### ISSUE TITLE
Support Java 16 (and higher)

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/ultimate#603]
### Resources
- [Migrating From JDK 8 to Later JDK Releases](https://docs.oracle.com/en/java/javase/16/migrate/migrating-jdk-8-later-jdk-releases.html#GUID-7744EF96-5899-4FB2-B34E-86D49B2E89B6)
- [JEP 403: Strongly Encapsulate JDK Internals (Java 17)](https://openjdk.org/jeps/403)

**Comment by schuessf** [comment]
Fixed by #672
