### ISSUE TITLE
Can this tool used in a real world project?

### ISSUE THREAD

**Issue by ConfZ** [ultimate-pa/ultimate#612]
Hi, I'd like to checking the non-termination of my real world project. Could please give me some advise to make it work on the hole project?

**Comment by danieldietsch** [comment]
Can you be more specific? What kind of project are you working on? You added ReqAnalyzer as label, but ReqAnalyzer is a tool that analyses requirements. I am not sure what non-termination is in this context.

**Comment by ConfZ** [comment]
> Can you be more specific? What kind of project are you working on? You added ReqAnalyzer as label, but ReqAnalyzer is a tool that analyses requirements. I am not sure what non-termination is in this context.

Im sorry for the wrong label... I am working on a C/C++ project, and as I know UAutomizer can work very well on SV-comp benchmark. However, I'd like to check the non-termination of a C++ project with about 50 C/C++ files rather than the code snippets, and I'm not sure if it can work. Shall I slice the code or input the single file to UAutomizer? Thanks!

**Comment by Heizmann** [comment]
We do support only C but not C++. If you preprocess your project and put everything into one file (e.g., by gcc) Ultimate Automizer should work on this file.
I can't remember the status of our support for taking a project as input. Maybe @danieldietsch can comment on that.

**Comment by danieldietsch** [comment]
Unfortunately, even a C project cannot be used as input at the moment.

**Comment by ConfZ** [comment]
> 

> Unfortunately, even a C project cannot be used as input at the moment.

What a pity, and still thanks for your reply. I have no other questions.

**Comment by ConfZ** [comment]
I have one more question, is UAutomizer can do unit test on function level?
