### ISSUE TITLE
Problems occured while trying to run Ultimate in linux virtual machine.

### ISSUE THREAD

**Issue by WHITE000CHOCOLATE** [ultimate-pa/ultimate#617]
### Basic Info
* Version: 0.2.2
* Java Version: Java 11
* error file: Ultimate_E4.17_Java11_Linux.target

### Description 
I tried to run Ultimate in Linux virtual machine using VMware, which have succeeded several months ago, but something wrong occured when I tapped "reload" in *_Linux.target. It shows as below:

Problems occurred while resolving the target contents
	Problems loading repositories
		Problems loading repositories
			HTTP Server 'Service Unavailable': https://monteverdi.informatik.uni-freiburg.de/nexus/content/repositories/eclipse-4.17/content.xml
		Problems loading repositories
			HTTP Server 'Service Unavailable': https://monteverdi.informatik.uni-freiburg.de/nexus/content/repositories/cdt-10.0/content.xml
		Problems loading repositories
			HTTP Server 'Service Unavailable': https://monteverdi.informatik.uni-freiburg.de/nexus/content/repositories/orbit-R20200831200620/content.xml

I tried to surf these url in Internet and failed as well, it all shows like this:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

I wonder if there is something wrong with the server, and what can I do except waiting? Thank you.

**Comment by danieldietsch** [comment]
You have to update from our latest dev, the URL has changed.

**Comment by WHITE000CHOCOLATE** [comment]
Oh I see! So can I only update the *.target file, or I must update the whole project to the latest version?

**Comment by danieldietsch** [comment]
It would be better to update the whole project, but you can -- probably -- make due whit the target files and the *.pom files.

**Comment by WHITE000CHOCOLATE** [comment]
ok. I solved the problem by reinstalling the whole project in a new folder. Thank you very much!
