### ISSUE TITLE
Fix examples\CToBoogieTranslation\UnsupportedInfinity.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#62]

**Comment by alexandernutz** [comment]
Throws "java.lang.UnsupportedOperationException: createNanOrInfinity is unsupported"
This seems to be intentional -- I would have to ask a float expert (Matthias) if there is a solution.

**Comment by danieldietsch** [comment]
@Heizmann any comments?

**Comment by danieldietsch** [comment]
This is the intended behavior.
