### ISSUE TITLE
Fix examples\CToBoogieTranslation\builtin_return_address.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#63]

**Comment by alexandernutz** [comment]
addressed in commit SHA: ed1022fc6a59e52fa2299d2b218512e854a19312
(still have to double check use of overapproximation flag)

**Comment by danieldietsch** [comment]
@alexandernutz: can you close the ticket when you have checked?

**Comment by alexandernutz** [comment]
seems to work fine
