### ISSUE TITLE
Update Ultimate framework components & dependencies

### ISSUE THREAD

**Issue by bahnwaerter** [ultimate-pa/ultimate#631]
Most of the used framework components and Java dependencies are outdated right now. Therefore an update of all used components and linked dependencies would be great. Such an update may consist of the following tasks:

- [ ] Optional: Replace Ant build tasks by Maven
- [ ] Migrate from JUnit 4 to JUnit 5
- [ ] Update Eclipse Platform to the latest release
- [ ] Update Eclipse CDT to to the latest release
- [ ] Migrate from Java 11 to Java 17 (addressed by issue #603)

**Comment by danieldietsch** [comment]
It might also be necessary to fully migrate to Eclipse E4 -- I am not sure if the latest Eclipse Platform still supports the E3 framework. This might require a rework of the GUI components.

**Comment by danieldietsch** [comment]
BTW: I would *really* like to have this done. The current state is a major source of tech debt in Ultimate.

**Comment by Heizmann** [comment]
I absolutely appreciate that. I won't we able to contribute before the end of the semester, maybe I can only contribute after I acquired more funding. So, don't wait for me to get this done.

**Comment by schuessf** [comment]
Fixed by #672
