### ISSUE TITLE
Fix examples\CToBoogieTranslation\builtin_strchr.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#64]

**Comment by alexandernutz** [comment]
support for function builtin_strchr added in commit SHA: 75e3a2217faf455ce7052c668bf5597772a33da8
open question: is the overapproximation flag used correctly

**Comment by alexandernutz** [comment]
slightly reworked the handling of overapproximation flags in the CTranslation in SHA c3b7d009ae9a6b9b6f85f3632f042aab91802a22
 --> should work now in this instance
