### ISSUE TITLE
Bug: Unsound unreach proof in Automizer, GemCutter

### ISSUE THREAD

**Issue by Novak756** [ultimate-pa/ultimate#646]
### Basic Info
* Version: `0.2.3-dev-bfb52b7`
* Java Version: 
    - openjdk 11.0.20.1 2023-08-24`
    - OpenJDK Runtime Environment `(build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04)`
    - OpenJDK 64-Bit Server VM `(build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)`
* Operating System: `Ubuntu 20.04.6 LTS (Focal Fossa)`
* Input file: 
```c
extern void __VERIFIER_error(void);
extern unsigned char __VERIFIER_nondet_uchar(void);

int main(){
	unsigned char c = __VERIFIER_nondet_uchar();
	if(!((((unsigned int) (((int) ((int) ((int)((c) - (48))) >> (int) ((unsigned int)(31))) >> (int) ((unsigned int)(31))) + ((int) ((int) ((int)((c) - (48))) >> (int) ((unsigned int)(31))) >> (int) ((unsigned int)(31))))) | ((int) (((unsigned int) (((int) ((int)((c) - (48))) >> (int) ((unsigned int)(31))) + ((int) ((int)((c) - (48))) >> (int) ((unsigned int)(31))))) | ((int) ((unsigned int) (((int)((c) - (48))) + ((int)((c) - (48))))) >> (int) ((unsigned int)(31)))) >> (int) ((unsigned int)(31)))) == ((unsigned int) 0))){
        __VERIFIER_error();
    }
    return 0;
}


```
* Settings: `Ultimate.py --architecture 64bit --spec unreach.prp --file bug.c`, with `bug.c` being the file above and unreach.prp containing `CHECK( init(main()), LTL(G ! call(reach_error())) )`
* Toolchain: Fails on Ultimate Automizer, Kojak and GemCutter, works on Taipan
* [Logs](https://github.com/ultimate-pa/ultimate/files/12652097/logs.zip)

### Description 
Automizer and GemCutter incorrectly prove unreachability of the `__VERIFIER_error()`, returning `TRUE` 
Kojak fails with the Error code `ERROR: ExceptionOrErrorResult: SMTLIBException: Sort BitVec not declared`
Taipan correctly finds the error and returns `FALSE`

**Comment by Novak756** [comment]
When running `./Ultimate -tc ./config/AutomizerReach.xml -s ./config/svcomp-Reach-64bit-Automizer_Bitvector.epf -i bug.c` all three tools are able to find the error, however the default behaviour is still incorrect.

**Comment by schuessf** [comment]
Thanks again for your report! There was once again an issue with the translation of bitwise operators (`|` in that case) to integers. It should be fixed now.
