### ISSUE TITLE
Fix examples\CToBoogieTranslation\floatToInt.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#65]

**Comment by alexandernutz** [comment]
After first glance:
The translation outputs a type unsafe Boggie program.
A variable called "ROUNDINGMODE_RTZ" (or similar) is not declared but used.
The function convertFLOATToINT is called with two arguments but declared with one.

**Comment by danieldietsch** [comment]
perhaps also a question for @Heizmann

**Comment by alexandernutz** [comment]
addition:
I observed this using default settings wrt. Float & Bitvector (at least there are no particular changes I made to the benchmark settings)

**Comment by danieldietsch** [comment]
Was fixed some time ago.
