### ISSUE TITLE
Web interface for Automata Library is broken

### ISSUE THREAD

**Issue by chrt** [ultimate-pa/ultimate#656]
# Basic Info
* Version: Ultimate version 0.2.3-dev-ab2f2ec-m ([web interface](https://www.ultimate-pa.org/?ui=int&tool=automata_library) for the Automata Library)
* Input file: The samples

# Description
The samples do not run. A runtime error is reported:
```
RuntimeException: java.lang.ClassNotFoundException: de.uni_freiburg.informatik.ultimate.automata.petrinet.unfolding.BuchiPetriNetUnfolder cannot be found by de.uni_freiburg.informatik.ultimate.plugins.generator.automatascriptinterpreter_0.2.3
```

It is true that there is no `BuchiPetriNetUnfolder.java` in that directory.

**Comment by schuessf** [comment]
We just updated our website, it should be fixed now (see 8162328)
