### ISSUE TITLE
Bug: Loop invariants in correctness witnesses produced by UAutomizer refer to out-of-bound variables

### ISSUE THREAD

**Issue by Po-Chun-Chien** [ultimate-pa/ultimate#660]
### Basic Info
* Version: 0e0057cc (downloaded from tool [archive](https://doi.org/10.5281/zenodo.10203545) of SV-COMP 2024)
* Input file: [`cal57.c`](https://gitlab.com/sosy-lab/research/data/word-level-hwmc-benchmarks/-/blob/6c2870427db379c9de050d54a1b74768b6a85d18/bv/c-eagerMod/goel-industry/cal57.c) with property [`unreach-call.prp`](https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks/-/blob/main/c/properties/unreach-call.prp)

### Description 

The loop invariant in a correctness witness generated by UAutomizer might contain out-of-bound program variables,
making the invariant syntactically incorrect.

Here's an example [witness](https://github.com/ultimate-pa/ultimate/files/14029003/witness.graphml.zip) obtained by running the following command:

```bash
./Ultimate.py --spec ../unreach-call.prp --file ../cal57.c --full-output --architecture 64bit
```

This is the invariant generated for the loop at [line 42](https://gitlab.com/sosy-lab/research/data/word-level-hwmc-benchmarks/-/blob/6c2870427db379c9de050d54a1b74768b6a85d18/bv/c-eagerMod/goel-industry/cal57.c#L42) of the program:

```xml
<node id="N29">
<data key="invariant">((((((((((1 == mask_SORT_1) &amp;&amp; (7 == mask_SORT_5)) &amp;&amp; (1 == var_31)) &amp;&amp; (0 == state_12)) &amp;&amp; (0 == state_18)) &amp;&amp; (var_15 == 0)) &amp;&amp; (1 == var_21)) &amp;&amp; (var_11 == 0)) || (((((((((1 == mask_SORT_1) &amp;&amp; (1 == state_12)) &amp;&amp; (1 == state_18)) &amp;&amp; (7 == mask_SORT_5)) &amp;&amp; (1 == var_31)) &amp;&amp; ((!((var_25 == 1)) &amp;&amp; !((var_20 == 1))) || ((var_20 == 1) &amp;&amp; (var_25 == 1)))) &amp;&amp; (var_15 == 0)) &amp;&amp; (1 == var_21)) &amp;&amp; (var_11 == 0))) || ((((((((1 == mask_SORT_1) &amp;&amp; (1 == state_12)) &amp;&amp; (7 == mask_SORT_5)) &amp;&amp; (1 == var_31)) &amp;&amp; (0 == state_18)) &amp;&amp; (var_15 == 0)) &amp;&amp; (1 == var_21)) &amp;&amp; (var_11 == 0)))</data>
```

The invariant refer to variables `var_20` and `var_25`,
which are declared inside the loop at line [68](https://gitlab.com/sosy-lab/research/data/word-level-hwmc-benchmarks/-/blob/6c2870427db379c9de050d54a1b74768b6a85d18/bv/c-eagerMod/goel-industry/cal57.c#L68) and [75](https://gitlab.com/sosy-lab/research/data/word-level-hwmc-benchmarks/-/blob/6c2870427db379c9de050d54a1b74768b6a85d18/bv/c-eagerMod/goel-industry/cal57.c#L75), respectively.
Therefore, the invariant is syntactically wrong.

**Comment by schuessf** [comment]
Thank you for your report! I just fixed this problem, we did not handle the scope of for-loops fully correct, as a for-loop has usually two scopes: the initializer and the body.
