### ISSUE TITLE
Fix examples\CToBoogieTranslation\innerouterAssertionError.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#68]

**Comment by alexandernutz** [comment]
gcc says this file contains invalid syntax --> postponing this test

gcc -std=c11 --pedantic innerouterAssertionError.c
innerouterAssertionError.c:8:18: Warnung: ISO-C verbietet Feld »maskarray_t« der Größe null [-Wpedantic]
 typedef uint32_t maskarray_t[0];
                  ^
innerouterAssertionError.c:10:52: Warnung: ISO-C verbietet leere Initialisierungsklammern [-Wpedantic]
 static maskarray_t via_pro_group_a_irqs[4U][5U]  = {};

**Comment by danieldietsch** [comment]
Should we try to find another trigger for this assertion or do you think this is caused by invalid C? We have many regressions because of this.

**Comment by danieldietsch** [comment]
One other example is ``Backtranslation/regression/c/standard/NestedArrays.c``
