### ISSUE TITLE
C backtranslation fails

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#7]
Input:programs/regression/c/BugForLoop01.c 
Settings:settings/automizer/TreeInterpolants.epf 
Toolchain:toolchains/AutomizerC.xml

fails as follows

NullPointerException: null: de.uni_freiburg.informatik.ultimate.plugins.generator.cacsl2boogietranslator.CACSL2BoogieBacktranslator$CheckForSubtreeInclusion.check(CACSL2BoogieBacktranslator.java:819)

**Comment by danieldietsch** [comment]
Not reproducible (anymore )
