### ISSUE TITLE
SyntaxChecker calls gcc 2 times

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#75]
In SyntaxChecker.doSyntaxCheck() the method callSytaxCheckerAndReturnStderrOutput is called two times, which leads to calling gcc with the same arguments two times. This seems wasteful.

**Comment by Heizmann** [comment]
One time it is called to check for errors, one time it is called to check for warnings.
Seems wasteful, but we already discussed this, there is no simple solution especially if we do not want to restrict ourselves to gcc.

**Comment by danieldietsch** [comment]
Why call it two times if the call is identical?
