### ISSUE TITLE
AutomataScriptInterpreterBenchmarkResults polluting webinterface results

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#76]
Either fix toolchain / settings or the toString method that is used in result generation. 

See https://monteverdi.informatik.uni-freiburg.de/tomcat/Website/?ui=int&tool=automata_script_interpreter for examples

**Comment by Heizmann** [comment]
Maybe Christian has some preferences how this should be fixed.

**Comment by schillic** [comment]
I prefer to filter those outputs completely.
Statistics are usually not interesting for the user; they are meant for benchmarking.
As the subject indicates, there is too much pollution with all the data reported.

**Comment by schillic** [comment]
This can be changed by making an option out of this private field:
https://github.com/ultimate-pa/ultimate/blob/dev/trunk/source/AutomataScriptInterpreter/src/de/uni_freiburg/informatik/ultimate/plugins/generator/automatascriptinterpreter/TestFileInterpreter.java#L673

**Comment by danieldietsch** [comment]
Will be addressed by implementing #88
