### ISSUE TITLE
Incorrect translation of switch statements

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#8]
We are unsound for the following input.

    Program:programs/regression/c/Switch02.c 
    Settings:settings/automizer/ForwardPredicates.epf 
    Toolchain:toolchains/AutomizerC.xml

Presumed problem: In contradicion to the C standard, the controlling expression is converted to int.

**Comment by alexandernutz** [comment]
should be fixed by commit 605b4c0f139afccce4c79503dd72aff74de12d17
