### ISSUE TITLE
Add Transformula Support for Abtract Interpretation

### ISSUE THREAD

**Issue by greitsch** [ultimate-pa/ultimate#84]

**Comment by danieldietsch** [comment]
In general, TFs are already supported by the fixpoint engine (cf. runFuture in AbstractInterpreter or VPDomain). The post operators for various domains are the main issue.

**Comment by greitsch** [comment]
This issue is left open intentionally. I first want to wait for the results of extensive testing in order to be certain that this issue can be closed.

**Comment by greitsch** [comment]
The transformula support for all Abstract Interpretation domains has beein implemented in the form of the PoormanAbstractDomain. If there is another method needed, please open a new ticket (and maybe reference this one).
