### ISSUE TITLE
Add support for  __builtin_unreachable

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#99]
Input:svcomp/ldv-linux-4.0-rc1-mav/linux-4.0-rc1---drivers--net--ethernet--atheros--atl1e--atl1e.ko_true-unreach-call.cil.c 
Settings:settings/svcomp2017/automizer/svcomp-Reach-32bit-Automizer_Bitvector.epf 
Toolchain:toolchains/AutomizerC.xml

Error message with -ea
``java.lang.AssertionError: a function that is called in the program is not declared in the program:__builtin_unreachable``

Error message without -ea
``NullPointerException: null: java.util.AbstractCollection.addAll(AbstractCollection.java:343)``

**Comment by danieldietsch** [comment]
gcc extension description: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
